import mysql from 'mysql2/promise';
import { v4 as uuidv4 } from 'uuid';

const db = mysql.createPool({
  host: '8.140.209.138',
  port: 9000,
  user: 'root',
  password: '123456',
  database: 'fmHome',
  waitForConnections: true,
  connectionLimit: 10,
});

async function query(sql, params = []) {
  const [rows] = await db.execute(sql, params);
  return rows;
}

const RECIPES = [
  {
    id: 'recipe-kung-pao-chicken',
    title: '宫保鸡丁',
    category: '下饭菜',
    difficulty: '中等',
    cookMinutes: 25,
    cookTime: '25分钟',
    description: '经典川菜，鸡肉嫩滑，花生香脆，麻辣鲜香。',
    tags: ['川菜', '下饭菜', '经典'],
    imageUrl: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=宫保鸡丁美食照片，高清，诱人，中式菜肴&image_size=portrait_4_3',
    tips: '鸡胸肉要提前腌制，花生要最后放保持脆感。',
    ingredients: [
      { name: '鸡胸肉', amount: '300g', category: '主料' },
      { name: '花生米', amount: '50g', category: '配料' },
      { name: '干辣椒', amount: '适量', category: '配料' },
      { name: '花椒', amount: '适量', category: '调料' },
      { name: '黄瓜', amount: '1根', category: '配料' },
      { name: '生抽', amount: '2勺', category: '调料' },
      { name: '醋', amount: '1勺', category: '调料' },
      { name: '糖', amount: '1勺', category: '调料' },
    ],
    steps: [
      { title: '腌制鸡肉', content: '鸡胸肉切丁，加生抽、淀粉、料酒腌制15分钟。' },
      { title: '调汁', content: '生抽、醋、糖、淀粉水混合成调味汁。' },
      { title: '炒花生', content: '小火炒香花生米，盛出备用。' },
      { title: '炒鸡丁', content: '热锅下油，放入鸡丁翻炒至变色盛出。' },
      { title: '爆香', content: '锅中放入干辣椒、花椒爆香，加入黄瓜丁翻炒。' },
      { title: '完成', content: '倒入鸡丁和花生米，淋入调味汁翻炒均匀即可。' },
    ],
  },
  {
    id: 'recipe-map-tofu',
    title: '麻婆豆腐',
    category: '下饭菜',
    difficulty: '简单',
    cookMinutes: 20,
    cookTime: '20分钟',
    description: '麻辣鲜香的经典川菜。豆腐嫩滑，肉末香浓。',
    tags: ['川菜', '下饭菜', '经典'],
    imageUrl: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=麻婆豆腐美食照片，高清，诱人，红油，中式菜肴&image_size=portrait_4_3',
    tips: '豆腐要选嫩豆腐，勾芡分两次更入味。',
    ingredients: [
      { name: '豆腐', amount: '1块', category: '主料' },
      { name: '猪肉末', amount: '100g', category: '主料' },
      { name: '豆瓣酱', amount: '2勺', category: '调料' },
      { name: '花椒粉', amount: '适量', category: '调料' },
      { name: '生抽', amount: '1勺', category: '调料' },
      { name: '淀粉', amount: '适量', category: '调料' },
      { name: '葱花', amount: '适量', category: '配料' },
    ],
    steps: [
      { title: '准备', content: '豆腐切块，焯水备用。' },
      { title: '炒肉末', content: '热锅下油，放入肉末炒至变色。' },
      { title: '调味', content: '加入豆瓣酱炒出红油，加生抽。' },
      { title: '烧豆腐', content: '放入豆腐块，加水烧5分钟。' },
      { title: '勾芡', content: '倒入水淀粉勾芡，撒花椒粉、葱花即可。' },
    ],
  },
  {
    id: 'recipe-egg-fried-rice',
    title: '蛋炒饭',
    category: '快手菜',
    difficulty: '简单',
    cookMinutes: 10,
    cookTime: '10分钟',
    description: '最简单也最考验功力的家常菜。粒粒分明，蛋香浓郁。',
    tags: ['快手菜', '主食', '经典'],
    imageUrl: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=蛋炒饭美食照片，高清，诱人，粒粒分明&image_size=portrait_4_3',
    tips: '要用隔夜饭，蛋液先裹饭再炒更香。',
    ingredients: [
      { name: '米饭', amount: '2碗', category: '主料' },
      { name: '鸡蛋', amount: '2个', category: '主料' },
      { name: '葱花', amount: '适量', category: '配料' },
      { name: '盐', amount: '适量', category: '调料' },
    ],
    steps: [
      { title: '打蛋', content: '鸡蛋打散，倒入米饭中拌匀。' },
      { title: '炒制', content: '热锅下油，倒入米饭大火翻炒。' },
      { title: '调味', content: '加盐调味，撒葱花翻炒均匀即可。' },
    ],
  },
  {
    id: 'recipe-tomato-egg',
    title: '番茄炒蛋',
    category: '下饭菜',
    difficulty: '简单',
    cookMinutes: 15,
    cookTime: '15分钟',
    description: '国民家常菜，酸甜可口，营养丰富。',
    tags: ['下饭菜', '快手菜', '经典'],
    imageUrl: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=番茄炒蛋美食照片，高清，诱人，红黄相间&image_size=portrait_4_3',
    tips: '先炒蛋盛出，再炒番茄出汁后混合。',
    ingredients: [
      { name: '番茄', amount: '2个', category: '主料' },
      { name: '鸡蛋', amount: '3个', category: '主料' },
      { name: '白糖', amount: '1勺', category: '调料' },
      { name: '盐', amount: '适量', category: '调料' },
      { name: '葱花', amount: '适量', category: '配料' },
    ],
    steps: [
      { title: '准备', content: '番茄切块，鸡蛋打散。' },
      { title: '炒蛋', content: '热锅下油，倒入蛋液炒熟盛出。' },
      { title: '炒番茄', content: '锅中放油，放入番茄炒出汁。' },
      { title: '混合', content: '倒入鸡蛋，加糖、盐调味，撒葱花即可。' },
    ],
  },
  {
    id: 'recipe-green-pepper-pork',
    title: '青椒肉丝',
    category: '下饭菜',
    difficulty: '简单',
    cookMinutes: 15,
    cookTime: '15分钟',
    description: '经典家常菜，肉丝嫩滑，青椒爽脆。',
    tags: ['下饭菜', '快手菜'],
    imageUrl: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=青椒肉丝美食照片，高清，诱人，中式炒菜&image_size=portrait_4_3',
    tips: '肉丝要逆纹切，加淀粉腌制更嫩。',
    ingredients: [
      { name: '猪里脊', amount: '200g', category: '主料' },
      { name: '青椒', amount: '2个', category: '主料' },
      { name: '生抽', amount: '2勺', category: '调料' },
      { name: '淀粉', amount: '适量', category: '调料' },
      { name: '姜蒜', amount: '适量', category: '配料' },
    ],
    steps: [
      { title: '腌制', content: '猪里脊切丝，加生抽、淀粉腌制。' },
      { title: '炒肉丝', content: '热锅下油，炒熟肉丝盛出。' },
      { title: '炒青椒', content: '放入姜蒜、青椒丝翻炒。' },
      { title: '完成', content: '倒入肉丝，加盐、生抽调味翻炒均匀。' },
    ],
  },
  {
    id: 'recipe-steamed-fish',
    title: '清蒸鲈鱼',
    category: '下饭菜',
    difficulty: '中等',
    cookMinutes: 20,
    cookTime: '20分钟',
    description: '鲜美嫩滑的经典蒸菜。鱼肉细嫩，豉油鲜香。',
    tags: ['蒸菜', '海鲜', '经典'],
    imageUrl: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=清蒸鲈鱼美食照片，高清，诱人，整条鱼，中式菜肴&image_size=portrait_4_3',
    tips: '鱼要新鲜，蒸的时间不能过长。',
    ingredients: [
      { name: '鲈鱼', amount: '1条', category: '主料' },
      { name: '葱段', amount: '适量', category: '配料' },
      { name: '姜片', amount: '适量', category: '配料' },
      { name: '蒸鱼豉油', amount: '3勺', category: '调料' },
      { name: '料酒', amount: '2勺', category: '调料' },
    ],
    steps: [
      { title: '处理鱼', content: '鲈鱼洗净，两面各划三刀，抹料酒。' },
      { title: '铺底', content: '盘中铺姜片和葱段，放上鲈鱼。' },
      { title: '蒸制', content: '水开后上锅蒸8-10分钟。' },
      { title: '淋油', content: '取出倒掉汤汁，淋蒸鱼豉油，撒葱丝，浇热油即可。' },
    ],
  },
  {
    id: 'recipe-braised-pork',
    title: '红烧肉',
    category: '下饭菜',
    difficulty: '困难',
    cookMinutes: 90,
    cookTime: '1.5小时',
    description: '经典硬菜，肥而不腻，入口即化。肉片方正，色泽红亮。',
    tags: ['下饭菜', '硬菜', '经典'],
    imageUrl: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=红烧肉美食照片，高清，诱人，红亮，中式硬菜&image_size=portrait_4_3',
    tips: '小火慢炖是关键，冰糖炒色更红亮。',
    ingredients: [
      { name: '五花肉', amount: '500g', category: '主料' },
      { name: '冰糖', amount: '适量', category: '调料' },
      { name: '生抽', amount: '3勺', category: '调料' },
      { name: '老抽', amount: '1勺', category: '调料' },
      { name: '料酒', amount: '2勺', category: '调料' },
      { name: '姜片', amount: '适量', category: '配料' },
      { name: '葱段', amount: '适量', category: '配料' },
      { name: '八角', amount: '2个', category: '调料' },
    ],
    steps: [
      { title: '焯水', content: '五花肉切块，冷水下锅焯水。' },
      { title: '炒糖色', content: '锅中放油，小火炒化冰糖至红棕色。' },
      { title: '上色', content: '放入肉块翻炒上色，加姜片、葱段、八角。' },
      { title: '调味', content: '加入生抽、老抽、料酒，加水没过肉。' },
      { title: '炖煮', content: '小火炖1小时，大火收汁即可。' },
    ],
  },
  {
    id: 'recipe-hot-sour-soup',
    title: '酸辣汤',
    category: '汤类',
    difficulty: '简单',
    cookMinutes: 15,
    cookTime: '15分钟',
    description: '酸辣开胃的经典汤品。汤浓味美，暖胃驱寒。',
    tags: ['汤类', '酸辣', '经典'],
    imageUrl: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=酸辣汤美食照片，高清，诱人，中式汤品&image_size=portrait_4_3',
    tips: '醋要最后放，保持酸味。胡椒粉适量。',
    ingredients: [
      { name: '豆腐', amount: '1块', category: '主料' },
      { name: '木耳', amount: '适量', category: '配料' },
      { name: '香菇', amount: '适量', category: '配料' },
      { name: '鸡蛋', amount: '1个', category: '主料' },
      { name: '醋', amount: '3勺', category: '调料' },
      { name: '胡椒粉', amount: '适量', category: '调料' },
      { name: '淀粉', amount: '适量', category: '调料' },
    ],
    steps: [
      { title: '准备', content: '豆腐、木耳、香菇切丝。' },
      { title: '煮汤', content: '锅中加水烧开，放入食材煮5分钟。' },
      { title: '勾芡', content: '倒入水淀粉勾芡。' },
      { title: '倒蛋液', content: '慢慢倒入蛋液形成蛋花。' },
      { title: '调味', content: '加醋、胡椒粉、盐调味即可。' },
    ],
  },
  {
    id: 'recipe-dongpo-pork',
    title: '东坡肉',
    category: '下饭菜',
    difficulty: '困难',
    cookMinutes: 120,
    cookTime: '2小时',
    description: '杭帮菜，入口即化。肉片方正，色泽红亮。',
    tags: ['杭帮菜', '下饭菜', '经典'],
    imageUrl: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=东坡肉美食照片，高清，诱人，红亮，中式硬菜&image_size=portrait_4_3',
    tips: '小火慢炖是关键，黄酒要多放。',
    ingredients: [
      { name: '五花肉', amount: '500g', category: '主料' },
      { name: '黄酒', amount: '200ml', category: '调料' },
      { name: '生抽', amount: '3勺', category: '调料' },
      { name: '老抽', amount: '1勺', category: '调料' },
      { name: '冰糖', amount: '适量', category: '调料' },
      { name: '姜片', amount: '适量', category: '配料' },
      { name: '葱段', amount: '适量', category: '配料' },
    ],
    steps: [
      { title: '焯水', content: '五花肉整块冷水下锅焯水。' },
      { title: '铺底', content: '砂锅底部铺上姜片和葱段。' },
      { title: '放肉', content: '放入五花肉，皮朝下。' },
      { title: '调味', content: '加入黄酒、生抽、老抽、冰糖。' },
      { title: '炖煮', content: '小火炖2小时，翻面再炖30分钟。' },
      { title: '收汁', content: '大火收汁至浓稠即可。' },
    ],
  },
  {
    id: 'recipe-mouth-water-chicken',
    title: '口水鸡',
    category: '凉菜',
    difficulty: '中等',
    cookMinutes: 30,
    cookTime: '30分钟',
    description: '麻辣鲜香的经典凉菜。鸡肉嫩滑，红油香辣。',
    tags: ['川菜', '凉菜', '经典'],
    imageUrl: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=口水鸡美食照片，高清，诱人，红油，凉菜&image_size=portrait_4_3',
    tips: '鸡要煮到刚熟，过冰水更嫩。',
    ingredients: [
      { name: '鸡腿', amount: '2个', category: '主料' },
      { name: '辣椒油', amount: '3勺', category: '调料' },
      { name: '生抽', amount: '3勺', category: '调料' },
      { name: '醋', amount: '1勺', category: '调料' },
      { name: '花椒粉', amount: '适量', category: '调料' },
      { name: '花生碎', amount: '适量', category: '配料' },
      { name: '葱花', amount: '适量', category: '配料' },
    ],
    steps: [
      { title: '煮鸡', content: '鸡腿冷水下锅煮15分钟至熟。' },
      { title: '过冰水', content: '捞出放入冰水中冷却。' },
      { title: '调汁', content: '辣椒油、生抽、醋、花椒粉混合。' },
      { title: '完成', content: '将调料淋在鸡块上，撒花生碎、葱花。' },
    ],
  },
  {
    id: 'recipe-plum-pork',
    title: '梅菜扣肉',
    category: '下饭菜',
    difficulty: '困难',
    cookMinutes: 120,
    cookTime: '2小时',
    description: '经典粤菜，肥而不腻。梅菜香浓，肉片软烂。',
    tags: ['粤菜', '下饭菜', '经典'],
    imageUrl: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=梅菜扣肉美食照片，高清，诱人，中式硬菜&image_size=portrait_4_3',
    tips: '肉要煮到筷子能扎透，蒸的时间要够。',
    ingredients: [
      { name: '五花肉', amount: '500g', category: '主料' },
      { name: '梅菜', amount: '100g', category: '配料' },
      { name: '生抽', amount: '2勺', category: '调料' },
      { name: '老抽', amount: '1勺', category: '调料' },
      { name: '料酒', amount: '2勺', category: '调料' },
      { name: '白糖', amount: '1勺', category: '调料' },
    ],
    steps: [
      { title: '煮肉', content: '五花肉整块冷水下锅煮30分钟。' },
      { title: '上色', content: '肉表面抹上老抽，炸至金黄。' },
      { title: '切片', content: '肉放凉后切成薄片。' },
      { title: '铺底', content: '梅菜铺在碗底，肉片码在上面。' },
      { title: '调味', content: '淋上生抽、料酒、糖的混合汁。' },
      { title: '蒸制', content: '上锅蒸1.5小时，倒扣装盘。' },
    ],
  },
  {
    id: 'recipe-steamed-shrimp',
    title: '蒜蓉粉丝蒸虾',
    category: '下饭菜',
    difficulty: '中等',
    cookMinutes: 20,
    cookTime: '20分钟',
    description: '鲜美可口的蒸菜。虾肉弹牙，粉丝吸汁。',
    tags: ['蒸菜', '海鲜', '经典'],
    imageUrl: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=蒜蓉粉丝蒸虾美食照片，高清，诱人，海鲜&image_size=portrait_4_3',
    tips: '虾要开背去虾线，粉丝泡软铺底。',
    ingredients: [
      { name: '虾', amount: '500g', category: '主料' },
      { name: '粉丝', amount: '1把', category: '配料' },
      { name: '蒜末', amount: '适量', category: '配料' },
      { name: '生抽', amount: '2勺', category: '调料' },
      { name: '蚝油', amount: '1勺', category: '调料' },
      { name: '葱花', amount: '适量', category: '配料' },
    ],
    steps: [
      { title: '准备', content: '粉丝泡软铺在盘底，虾开背去虾线放在粉丝上。' },
      { title: '炒蒜蓉', content: '锅中放油，炒香蒜末。' },
      { title: '调味', content: '加入生抽、蚝油混合。' },
      { title: '淋汁', content: '将蒜蓉汁淋在虾上。' },
      { title: '蒸制', content: '水开后上锅蒸8-10分钟。' },
      { title: '完成', content: '撒上葱花即可。' },
    ],
  },
  {
    id: 'recipe-sweet-sour-loin',
    title: '糖醋里脊',
    category: '下饭菜',
    difficulty: '中等',
    cookMinutes: 30,
    cookTime: '30分钟',
    description: '酸甜可口的经典菜肴。外酥里嫩，色泽红亮。',
    tags: ['下饭菜', '酸甜', '经典'],
    imageUrl: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=糖醋里脊美食照片，高清，诱人，红亮&image_size=portrait_4_3',
    tips: '里脊肉要切均匀，挂糊要薄。',
    ingredients: [
      { name: '猪里脊', amount: '400g', category: '主料' },
      { name: '白糖', amount: '3勺', category: '调料' },
      { name: '醋', amount: '4勺', category: '调料' },
      { name: '番茄酱', amount: '3勺', category: '调料' },
      { name: '淀粉', amount: '适量', category: '调料' },
      { name: '鸡蛋', amount: '1个', category: '调料' },
      { name: '盐', amount: '适量', category: '调料' },
    ],
    steps: [
      { title: '腌制', content: '里脊肉切条，加盐腌制。' },
      { title: '挂糊', content: '裹上淀粉和蛋清的混合物。' },
      { title: '炸制', content: '锅中放油，炸至金黄酥脆。' },
      { title: '调汁', content: '糖、醋、番茄酱、淀粉水混合。' },
      { title: '完成', content: '锅中倒入糖醋汁煮至浓稠，放入里脊翻炒。' },
    ],
  },
  {
    id: 'recipe-lotus-root-soup',
    title: '莲藕排骨汤',
    category: '汤类',
    difficulty: '简单',
    cookMinutes: 60,
    cookTime: '1小时',
    description: '清甜粉糯的经典汤品。莲藕粉糯，排骨软烂。',
    tags: ['汤类', '清甜', '营养'],
    imageUrl: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=莲藕排骨汤美食照片，高清，诱人，中式汤品&image_size=portrait_4_3',
    tips: '莲藕要选粉藕，小火慢炖。',
    ingredients: [
      { name: '排骨', amount: '500g', category: '主料' },
      { name: '莲藕', amount: '2节', category: '主料' },
      { name: '姜片', amount: '适量', category: '配料' },
      { name: '葱段', amount: '适量', category: '配料' },
      { name: '盐', amount: '适量', category: '调料' },
    ],
    steps: [
      { title: '焯水', content: '排骨冷水下锅焯水。' },
      { title: '炖排骨', content: '砂锅中加水，放入排骨、姜片炖40分钟。' },
      { title: '加莲藕', content: '放入莲藕块炖20分钟。' },
      { title: '调味', content: '加盐调味即可。' },
    ],
  },
  {
    id: 'recipe-kung-pao-shrimp',
    title: '宫保虾球',
    category: '下饭菜',
    difficulty: '中等',
    cookMinutes: 20,
    cookTime: '20分钟',
    description: '虾肉弹牙，花生香脆。麻辣鲜香，下饭神器。',
    tags: ['下饭菜', '海鲜', '快手'],
    imageUrl: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=宫保虾球美食照片，高清，诱人，海鲜&image_size=portrait_4_3',
    tips: '虾要去虾线，加料酒腌制。',
    ingredients: [
      { name: '虾', amount: '400g', category: '主料' },
      { name: '花生米', amount: '50g', category: '配料' },
      { name: '干辣椒', amount: '适量', category: '配料' },
      { name: '花椒', amount: '适量', category: '调料' },
      { name: '黄瓜', amount: '1根', category: '配料' },
      { name: '生抽', amount: '2勺', category: '调料' },
      { name: '醋', amount: '1勺', category: '调料' },
      { name: '糖', amount: '1勺', category: '调料' },
    ],
    steps: [
      { title: '准备', content: '虾去壳去虾线，加料酒腌制。' },
      { title: '炒花生', content: '小火炒香花生米。' },
      { title: '炒虾', content: '热锅下油，炒熟虾球盛出。' },
      { title: '爆香', content: '放入干辣椒、花椒爆香。' },
      { title: '调味', content: '加入黄瓜丁、生抽、醋、糖。' },
      { title: '完成', content: '倒入虾球和花生米翻炒均匀。' },
    ],
  },
  {
    id: 'recipe-oyster-beef',
    title: '蚝油牛肉',
    category: '下饭菜',
    difficulty: '中等',
    cookMinutes: 20,
    cookTime: '20分钟',
    description: '牛肉嫩滑，蚝油鲜香。经典粤菜，下饭神器。',
    tags: ['下饭菜', '牛肉', '经典'],
    imageUrl: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=蚝油牛肉美食照片，高清，诱人，中式炒菜&image_size=portrait_4_3',
    tips: '牛肉要逆纹切，腌制时加淀粉。',
    ingredients: [
      { name: '牛肉', amount: '300g', category: '主料' },
      { name: '蚝油', amount: '3勺', category: '调料' },
      { name: '生抽', amount: '2勺', category: '调料' },
      { name: '淀粉', amount: '适量', category: '调料' },
      { name: '姜蒜', amount: '适量', category: '配料' },
      { name: '青椒', amount: '2个', category: '配料' },
    ],
    steps: [
      { title: '腌制', content: '牛肉切片，加生抽、淀粉腌制。' },
      { title: '炒牛肉', content: '热锅下油，炒熟牛肉盛出。' },
      { title: '炒配菜', content: '放入姜蒜、青椒翻炒。' },
      { title: '调味', content: '加入蚝油、生抽。' },
      { title: '完成', content: '倒入牛肉翻炒均匀即可。' },
    ],
  },
  {
    id: 'recipe-dry-fried-beans',
    title: '干煸四季豆',
    category: '素菜',
    difficulty: '简单',
    cookMinutes: 15,
    cookTime: '15分钟',
    description: '干香爽口的经典素菜。四季豆皱皮，肉末香浓。',
    tags: ['素菜', '下饭菜', '经典'],
    imageUrl: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=干煸四季豆美食照片，高清，诱人，中式素菜&image_size=portrait_4_3',
    tips: '四季豆要煸到起皱，一定要炒熟。',
    ingredients: [
      { name: '四季豆', amount: '400g', category: '主料' },
      { name: '猪肉末', amount: '50g', category: '配料' },
      { name: '干辣椒', amount: '适量', category: '配料' },
      { name: '花椒', amount: '适量', category: '调料' },
      { name: '生抽', amount: '2勺', category: '调料' },
      { name: '盐', amount: '适量', category: '调料' },
    ],
    steps: [
      { title: '准备', content: '四季豆去筋切段。' },
      { title: '煸豆', content: '锅中放油，放入四季豆煸炒至起皱。' },
      { title: '炒肉末', content: '盛出四季豆，炒香肉末。' },
      { title: '完成', content: '放入四季豆、干辣椒、花椒、生抽翻炒均匀。' },
    ],
  },
  {
    id: 'recipe-spicy-crispy-tofu',
    title: '辣子鸡',
    category: '下饭菜',
    difficulty: '中等',
    cookMinutes: 35,
    cookTime: '35分钟',
    description: '麻辣鲜香的经典川菜。鸡肉外酥里嫩，辣椒满盆。',
    tags: ['川菜', '下饭菜', '经典'],
    imageUrl: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=辣子鸡美食照片，高清，诱人，红辣椒，中式菜肴&image_size=portrait_4_3',
    tips: '鸡块要炸到外酥里嫩，辣椒要多放。',
    ingredients: [
      { name: '鸡腿肉', amount: '400g', category: '主料' },
      { name: '干辣椒', amount: '100g', category: '配料' },
      { name: '花椒', amount: '适量', category: '调料' },
      { name: '姜蒜', amount: '适量', category: '配料' },
      { name: '生抽', amount: '2勺', category: '调料' },
      { name: '料酒', amount: '2勺', category: '调料' },
      { name: '淀粉', amount: '适量', category: '调料' },
    ],
    steps: [
      { title: '腌制', content: '鸡腿肉切块，加生抽、料酒、淀粉腌制。' },
      { title: '炸制', content: '锅中放油，炸鸡块至金黄酥脆。' },
      { title: '爆香', content: '锅中留底油，放入干辣椒、花椒、姜蒜爆香。' },
      { title: '完成', content: '倒入鸡块翻炒均匀即可。' },
    ],
  },
  {
    id: 'recipe-egg-drop-soup',
    title: '紫菜蛋花汤',
    category: '汤类',
    difficulty: '简单',
    cookMinutes: 10,
    cookTime: '10分钟',
    description: '最简单也最鲜美的汤品。紫菜鲜香，蛋花嫩滑。',
    tags: ['汤类', '快手菜', '经典'],
    imageUrl: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=紫菜蛋花汤美食照片，高清，诱人，中式汤品&image_size=portrait_4_3',
    tips: '水开后慢慢倒蛋液，形成漂亮的蛋花。',
    ingredients: [
      { name: '紫菜', amount: '1张', category: '主料' },
      { name: '鸡蛋', amount: '2个', category: '主料' },
      { name: '盐', amount: '适量', category: '调料' },
      { name: '香油', amount: '适量', category: '调料' },
      { name: '葱花', amount: '适量', category: '配料' },
    ],
    steps: [
      { title: '准备', content: '紫菜泡发，鸡蛋打散。' },
      { title: '煮汤', content: '锅中加水烧开，放入紫菜。' },
      { title: '倒蛋液', content: '慢慢倒入蛋液，用筷子轻轻搅拌。' },
      { title: '调味', content: '加盐、香油、葱花即可。' },
    ],
  },
  {
    id: 'recipe-stir-fry-mixed-veg',
    title: '清炒时蔬',
    category: '素菜',
    difficulty: '简单',
    cookMinutes: 10,
    cookTime: '10分钟',
    description: '清爽健康的家常素菜。保持蔬菜原味，简单快手。',
    tags: ['素菜', '快手菜', '健康'],
    imageUrl: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=清炒时蔬美食照片，高清，诱人，绿色蔬菜&image_size=portrait_4_3',
    tips: '大火快炒，保持蔬菜脆嫩。',
    ingredients: [
      { name: '时令蔬菜', amount: '400g', category: '主料' },
      { name: '蒜末', amount: '适量', category: '配料' },
      { name: '盐', amount: '适量', category: '调料' },
      { name: '油', amount: '适量', category: '调料' },
    ],
    steps: [
      { title: '准备', content: '蔬菜洗净切段。' },
      { title: '爆香', content: '热锅下油，放入蒜末爆香。' },
      { title: '炒制', content: '大火放入蔬菜快速翻炒。' },
      { title: '调味', content: '加盐调味，翻炒均匀即可。' },
    ],
  },
  {
    id: 'recipe-braised-eggplant',
    title: '红烧茄子',
    category: '素菜',
    difficulty: '简单',
    cookMinutes: 20,
    cookTime: '20分钟',
    description: '软糯入味的经典素菜。茄子吸汁，酱香浓郁。',
    tags: ['素菜', '下饭菜', '经典'],
    imageUrl: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=红烧茄子美食照片，高清，诱人，紫亮&image_size=portrait_4_3',
    tips: '茄子切块后撒盐腌制，减少吸油。',
    ingredients: [
      { name: '茄子', amount: '2根', category: '主料' },
      { name: '蒜末', amount: '适量', category: '配料' },
      { name: '生抽', amount: '2勺', category: '调料' },
      { name: '老抽', amount: '1勺', category: '调料' },
      { name: '白糖', amount: '1勺', category: '调料' },
      { name: '淀粉', amount: '适量', category: '调料' },
    ],
    steps: [
      { title: '准备', content: '茄子切块，撒盐腌制10分钟。' },
      { title: '煎制', content: '锅中放油，放入茄子煎至软糯。' },
      { title: '调味', content: '加入蒜末、生抽、老抽、糖。' },
      { title: '勾芡', content: '倒入水淀粉勾芡即可。' },
    ],
  },
  {
    id: 'recipe-fish-flavored-shredded-pork',
    title: '鱼香肉丝',
    category: '下饭菜',
    difficulty: '中等',
    cookMinutes: 25,
    cookTime: '25分钟',
    description: '酸甜辣香的经典川菜。肉丝嫩滑，配菜爽脆。',
    tags: ['川菜', '下饭菜', '经典'],
    imageUrl: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=鱼香肉丝美食照片，高清，诱人，红亮&image_size=portrait_4_3',
    tips: '鱼香汁的比例是关键：糖醋生抽1:1:1。',
    ingredients: [
      { name: '猪里脊', amount: '300g', category: '主料' },
      { name: '木耳', amount: '适量', category: '配料' },
      { name: '胡萝卜', amount: '1根', category: '配料' },
      { name: '青椒', amount: '1个', category: '配料' },
      { name: '白糖', amount: '2勺', category: '调料' },
      { name: '醋', amount: '2勺', category: '调料' },
      { name: '生抽', amount: '2勺', category: '调料' },
      { name: '豆瓣酱', amount: '1勺', category: '调料' },
      { name: '淀粉', amount: '适量', category: '调料' },
    ],
    steps: [
      { title: '腌制', content: '猪里脊切丝，加淀粉、料酒腌制。' },
      { title: '调汁', content: '糖、醋、生抽、淀粉水混合成鱼香汁。' },
      { title: '炒肉丝', content: '热锅下油，炒熟肉丝盛出。' },
      { title: '炒配菜', content: '放入木耳、胡萝卜、青椒丝翻炒。' },
      { title: '完成', content: '倒入肉丝和鱼香汁，加豆瓣酱翻炒均匀。' },
    ],
  },
  {
    id: 'recipe-chicken-mushroom',
    title: '小鸡炖蘑菇',
    category: '下饭菜',
    difficulty: '中等',
    cookMinutes: 60,
    cookTime: '1小时',
    description: '东北名菜，鲜美浓郁。鸡肉嫩滑，蘑菇香浓。',
    tags: ['东北菜', '下饭菜', '经典'],
    imageUrl: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=小鸡炖蘑菇美食照片，高清，诱人，中式炖菜&image_size=portrait_4_3',
    tips: '蘑菇要选干蘑菇，提前泡发更香。',
    ingredients: [
      { name: '鸡腿', amount: '4个', category: '主料' },
      { name: '干蘑菇', amount: '50g', category: '主料' },
      { name: '粉条', amount: '适量', category: '配料' },
      { name: '姜片', amount: '适量', category: '配料' },
      { name: '葱段', amount: '适量', category: '配料' },
      { name: '生抽', amount: '3勺', category: '调料' },
      { name: '料酒', amount: '2勺', category: '调料' },
    ],
    steps: [
      { title: '泡蘑菇', content: '干蘑菇提前泡发30分钟。' },
      { title: '焯水', content: '鸡腿切块，冷水下锅焯水。' },
      { title: '炒制', content: '热锅下油，放入鸡肉翻炒上色。' },
      { title: '炖煮', content: '加入蘑菇、姜片、葱段、生抽、料酒，加水炖40分钟。' },
      { title: '加粉条', content: '放入粉条再炖10分钟即可。' },
    ],
  },
  {
    id: 'recipe-pork-cabbage',
    title: '猪肉白菜炖粉条',
    category: '下饭菜',
    difficulty: '简单',
    cookMinutes: 40,
    cookTime: '40分钟',
    description: '东北家常菜，温暖实惠。白菜清甜，粉条滑嫩。',
    tags: ['东北菜', '下饭菜', '家常'],
    imageUrl: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=猪肉白菜炖粉条美食照片，高清，诱人，中式炖菜&image_size=portrait_4_3',
    tips: '粉条要提前泡软，白菜要选嫩叶。',
    ingredients: [
      { name: '五花肉', amount: '200g', category: '主料' },
      { name: '白菜', amount: '400g', category: '主料' },
      { name: '粉条', amount: '1把', category: '主料' },
      { name: '姜片', amount: '适量', category: '配料' },
      { name: '生抽', amount: '2勺', category: '调料' },
      { name: '盐', amount: '适量', category: '调料' },
    ],
    steps: [
      { title: '准备', content: '粉条泡软，白菜切块，五花肉切片。' },
      { title: '炒肉', content: '热锅下油，放入五花肉炒至微黄。' },
      { title: '炖煮', content: '加入白菜、姜片、生抽，加水炖20分钟。' },
      { title: '加粉条', content: '放入粉条炖10分钟，加盐调味即可。' },
    ],
  },
  {
    id: 'recipe-mapo-tofu-minced',
    title: '酸菜鱼',
    category: '下饭菜',
    difficulty: '中等',
    cookMinutes: 30,
    cookTime: '30分钟',
    description: '酸辣鲜美的经典川菜。鱼片嫩滑，酸菜开胃。',
    tags: ['川菜', '下饭菜', '海鲜'],
    imageUrl: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=酸菜鱼美食照片，高清，诱人，酸辣，中式菜肴&image_size=portrait_4_3',
    tips: '鱼片要薄，酸菜要炒香。',
    ingredients: [
      { name: '草鱼', amount: '1条', category: '主料' },
      { name: '酸菜', amount: '200g', category: '主料' },
      { name: '干辣椒', amount: '适量', category: '配料' },
      { name: '花椒', amount: '适量', category: '调料' },
      { name: '姜蒜', amount: '适量', category: '配料' },
      { name: '料酒', amount: '2勺', category: '调料' },
      { name: '淀粉', amount: '适量', category: '调料' },
    ],
    steps: [
      { title: '处理鱼', content: '草鱼去骨切片，加淀粉、料酒腌制。' },
      { title: '炒酸菜', content: '热锅下油，放入酸菜、姜蒜炒香。' },
      { title: '煮汤', content: '加水烧开，放入鱼骨煮10分钟。' },
      { title: '下鱼片', content: '放入鱼片煮3分钟至变色。' },
      { title: '淋油', content: '撒上干辣椒、花椒，浇热油即可。' },
    ],
  },
  {
    id: 'recipe-stir-fried-noodles',
    title: '炒面',
    category: '快手菜',
    difficulty: '简单',
    cookMinutes: 15,
    cookTime: '15分钟',
    description: '简单快捷的主食。面条筋道，配菜丰富。',
    tags: ['快手菜', '主食', '经典'],
    imageUrl: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=炒面美食照片，高清，诱人，中式炒面&image_size=portrait_4_3',
    tips: '面条煮到八分熟，过凉水更筋道。',
    ingredients: [
      { name: '面条', amount: '200g', category: '主料' },
      { name: '鸡蛋', amount: '1个', category: '主料' },
      { name: '卷心菜', amount: '适量', category: '配料' },
      { name: '胡萝卜', amount: '适量', category: '配料' },
      { name: '生抽', amount: '2勺', category: '调料' },
      { name: '老抽', amount: '1勺', category: '调料' },
    ],
    steps: [
      { title: '煮面', content: '面条煮到八分熟，过凉水沥干。' },
      { title: '炒蛋', content: '热锅下油，炒熟鸡蛋。' },
      { title: '炒配菜', content: '放入卷心菜丝、胡萝卜丝翻炒。' },
      { title: '炒面', content: '放入面条，加生抽、老抽翻炒均匀。' },
    ],
  },
  {
    id: 'recipe-braised-chicken-rice',
    title: '黄焖鸡米饭',
    category: '下饭菜',
    difficulty: '中等',
    cookMinutes: 40,
    cookTime: '40分钟',
    description: ' popular快餐美食。鸡肉嫩滑，汤汁浓郁。',
    tags: ['下饭菜', '经典', ' popular'],
    imageUrl: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=黄焖鸡米饭美食照片，高清，诱人，中式菜肴&image_size=portrait_4_3',
    tips: '鸡腿肉比鸡胸肉更嫩，香菇要提前泡发。',
    ingredients: [
      { name: '鸡腿肉', amount: '400g', category: '主料' },
      { name: '香菇', amount: '6朵', category: '配料' },
      { name: '青椒', amount: '2个', category: '配料' },
      { name: '姜片', amount: '适量', category: '配料' },
      { name: '生抽', amount: '3勺', category: '调料' },
      { name: '老抽', amount: '1勺', category: '调料' },
      { name: '料酒', amount: '2勺', category: '调料' },
      { name: '冰糖', amount: '适量', category: '调料' },
    ],
    steps: [
      { title: '准备', content: '鸡腿肉切块，香菇泡发。' },
      { title: '炒制', content: '热锅下油，放入鸡肉翻炒上色。' },
      { title: '调味', content: '加入姜片、香菇、生抽、老抽、料酒、冰糖。' },
      { title: '炖煮', content: '加水炖25分钟，放入青椒翻炒即可。' },
    ],
  },
  {
    id: 'recipe-fried-dumplings',
    title: '煎饺',
    category: '快手菜',
    difficulty: '简单',
    cookMinutes: 20,
    cookTime: '20分钟',
    description: '外酥里嫩的美味主食。底部金黄酥脆，馅料鲜美。',
    tags: ['快手菜', '主食', '经典'],
    imageUrl: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=煎饺美食照片，高清，诱人，金黄酥脆&image_size=portrait_4_3',
    tips: '火要中小火，加水盖盖焖熟。',
    ingredients: [
      { name: '饺子', amount: '15个', category: '主料' },
      { name: '油', amount: '适量', category: '调料' },
      { name: '水', amount: '适量', category: '调料' },
    ],
    steps: [
      { title: '煎制', content: '平底锅放油，放入饺子煎至底部微黄。' },
      { title: '焖熟', content: '加水盖盖，中小火焖8分钟。' },
      { title: '完成', content: '打开盖子，煎至底部金黄酥脆即可。' },
    ],
  },
  {
    id: 'recipe-cola-chicken-wings',
    title: '可乐鸡翅',
    category: '下饭菜',
    difficulty: '简单',
    cookMinutes: 25,
    cookTime: '25分钟',
    description: '甜香入味的经典菜肴。鸡翅嫩滑，色泽红亮。',
    tags: ['下饭菜', '快手菜', '经典'],
    imageUrl: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=可乐鸡翅美食照片，高清，诱人，红亮&image_size=portrait_4_3',
    tips: '鸡翅要两面划刀，可乐要没过鸡翅。',
    ingredients: [
      { name: '鸡翅', amount: '8个', category: '主料' },
      { name: '可乐', amount: '1罐', category: '调料' },
      { name: '生抽', amount: '2勺', category: '调料' },
      { name: '老抽', amount: '1勺', category: '调料' },
      { name: '姜片', amount: '适量', category: '配料' },
    ],
    steps: [
      { title: '处理鸡翅', content: '鸡翅两面划刀，焯水备用。' },
      { title: '煎制', content: '热锅下油，放入鸡翅煎至两面金黄。' },
      { title: '调味', content: '加入可乐、生抽、老抽、姜片。' },
      { title: '收汁', content: '大火烧开转小火炖15分钟，大火收汁即可。' },
    ],
  },
  {
    id: 'recipe-muxu-rou',
    title: '木须肉',
    category: '下饭菜',
    difficulty: '简单',
    cookMinutes: 20,
    cookTime: '20分钟',
    description: '经典鲁菜，营养丰富。鸡蛋嫩滑，肉片香嫩。',
    tags: ['鲁菜', '下饭菜', '经典'],
    imageUrl: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=木须肉美食照片，高清，诱人，中式炒菜&image_size=portrait_4_3',
    tips: '鸡蛋要先炒熟盛出，最后再混合。',
    ingredients: [
      { name: '猪里脊', amount: '200g', category: '主料' },
      { name: '鸡蛋', amount: '2个', category: '主料' },
      { name: '木耳', amount: '适量', category: '配料' },
      { name: '黄瓜', amount: '1根', category: '配料' },
      { name: '生抽', amount: '2勺', category: '调料' },
      { name: '盐', amount: '适量', category: '调料' },
    ],
    steps: [
      { title: '腌制', content: '猪里脊切片，加淀粉腌制。' },
      { title: '炒蛋', content: '热锅下油，炒熟鸡蛋盛出。' },
      { title: '炒肉', content: '放入肉片炒至变色。' },
      { title: '完成', content: '加入木耳、黄瓜、鸡蛋、生抽、盐翻炒均匀。' },
    ],
  },
  {
    id: 'recipe-huiguorou',
    title: '回锅肉',
    category: '下饭菜',
    difficulty: '中等',
    cookMinutes: 30,
    cookTime: '30分钟',
    description: '经典川菜，肥而不腻。肉片卷曲，豆瓣酱香。',
    tags: ['川菜', '下饭菜', '经典'],
    imageUrl: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=回锅肉美食照片，高清，诱人，红亮，中式菜肴&image_size=portrait_4_3',
    tips: '肉要煮到筷子能扎透，切片要薄。',
    ingredients: [
      { name: '五花肉', amount: '300g', category: '主料' },
      { name: '青蒜', amount: '4根', category: '主料' },
      { name: '豆瓣酱', amount: '2勺', category: '调料' },
      { name: '生抽', amount: '1勺', category: '调料' },
      { name: '甜面酱', amount: '1勺', category: '调料' },
      { name: '姜片', amount: '适量', category: '配料' },
    ],
    steps: [
      { title: '煮肉', content: '五花肉整块冷水下锅煮20分钟。' },
      { title: '切片', content: '肉放凉后切成薄片。' },
      { title: '炒制', content: '热锅下油，放入肉片炒至卷曲。' },
      { title: '调味', content: '加入豆瓣酱、甜面酱、生抽翻炒。' },
      { title: '完成', content: '放入青蒜段翻炒均匀即可。' },
    ],
  },
  {
    id: 'recipe-fanqie-niunan',
    title: '番茄牛腩汤',
    category: '汤类',
    difficulty: '中等',
    cookMinutes: 90,
    cookTime: '1.5小时',
    description: '酸甜浓郁的滋补汤品。牛腩软烂，番茄鲜香。',
    tags: ['汤类', '营养', '经典'],
    imageUrl: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=番茄牛腩汤美食照片，高清，诱人，红亮，中式汤品&image_size=portrait_4_3',
    tips: '牛腩要选带筋的，小火慢炖更软烂。',
    ingredients: [
      { name: '牛腩', amount: '500g', category: '主料' },
      { name: '番茄', amount: '3个', category: '主料' },
      { name: '姜片', amount: '适量', category: '配料' },
      { name: '葱段', amount: '适量', category: '配料' },
      { name: '番茄酱', amount: '2勺', category: '调料' },
      { name: '盐', amount: '适量', category: '调料' },
    ],
    steps: [
      { title: '焯水', content: '牛腩切块，冷水下锅焯水。' },
      { title: '炖牛腩', content: '砂锅中加水，放入牛腩、姜片炖1小时。' },
      { title: '加番茄', content: '放入番茄块、番茄酱再炖20分钟。' },
      { title: '调味', content: '加盐、葱段调味即可。' },
    ],
  },
  {
    id: 'recipe-jiucaichao-jidan',
    title: '韭菜炒鸡蛋',
    category: '素菜',
    difficulty: '简单',
    cookMinutes: 10,
    cookTime: '10分钟',
    description: '经典家常菜，简单快手。韭菜鲜香，鸡蛋嫩滑。',
    tags: ['素菜', '快手菜', '经典'],
    imageUrl: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=韭菜炒鸡蛋美食照片，高清，诱人，绿黄相间&image_size=portrait_4_3',
    tips: '韭菜要大火快炒，保持脆嫩。',
    ingredients: [
      { name: '韭菜', amount: '200g', category: '主料' },
      { name: '鸡蛋', amount: '3个', category: '主料' },
      { name: '盐', amount: '适量', category: '调料' },
      { name: '油', amount: '适量', category: '调料' },
    ],
    steps: [
      { title: '准备', content: '韭菜切段，鸡蛋打散。' },
      { title: '炒蛋', content: '热锅下油，倒入蛋液炒熟盛出。' },
      { title: '炒韭菜', content: '锅中放油，大火放入韭菜快速翻炒。' },
      { title: '完成', content: '倒入鸡蛋，加盐翻炒均匀即可。' },
    ],
  },
  {
    id: 'recipe-hongshao-tudou',
    title: '红烧土豆',
    category: '素菜',
    difficulty: '简单',
    cookMinutes: 20,
    cookTime: '20分钟',
    description: '软糯入味的经典素菜。土豆绵软，酱香浓郁。',
    tags: ['素菜', '下饭菜', '家常'],
    imageUrl: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=红烧土豆美食照片，高清，诱人，红亮&image_size=portrait_4_3',
    tips: '土豆要选黄心的，炖到筷子能扎透。',
    ingredients: [
      { name: '土豆', amount: '3个', category: '主料' },
      { name: '生抽', amount: '2勺', category: '调料' },
      { name: '老抽', amount: '1勺', category: '调料' },
      { name: '白糖', amount: '1勺', category: '调料' },
      { name: '姜片', amount: '适量', category: '配料' },
    ],
    steps: [
      { title: '准备', content: '土豆去皮切块。' },
      { title: '煎制', content: '锅中放油，放入土豆煎至表面微黄。' },
      { title: '调味', content: '加入姜片、生抽、老抽、糖。' },
      { title: '炖煮', content: '加水炖10分钟，大火收汁即可。' },
    ],
  },
  {
    id: 'recipe-laziding',
    title: '辣子鸡丁',
    category: '下饭菜',
    difficulty: '中等',
    cookMinutes: 30,
    cookTime: '30分钟',
    description: '麻辣鲜香的下饭菜。鸡丁外酥里嫩，辣椒满盆。',
    tags: ['川菜', '下饭菜', '辣'],
    imageUrl: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=辣子鸡丁美食照片，高清，诱人，红辣椒&image_size=portrait_4_3',
    tips: '鸡丁要炸到外酥里嫩，辣椒要多。',
    ingredients: [
      { name: '鸡腿肉', amount: '400g', category: '主料' },
      { name: '干辣椒', amount: '80g', category: '配料' },
      { name: '花椒', amount: '适量', category: '调料' },
      { name: '姜蒜', amount: '适量', category: '配料' },
      { name: '料酒', amount: '2勺', category: '调料' },
      { name: '淀粉', amount: '适量', category: '调料' },
    ],
    steps: [
      { title: '腌制', content: '鸡腿肉切丁，加料酒、淀粉腌制。' },
      { title: '炸制', content: '锅中放油，炸鸡丁至金黄酥脆。' },
      { title: '爆香', content: '锅中留底油，放入干辣椒、花椒、姜蒜爆香。' },
      { title: '完成', content: '倒入鸡丁翻炒均匀即可。' },
    ],
  },
  {
    id: 'recipe-donggua-paigu',
    title: '冬瓜排骨汤',
    category: '汤类',
    difficulty: '简单',
    cookMinutes: 50,
    cookTime: '50分钟',
    description: '清甜解暑的经典汤品。冬瓜透明，排骨软烂。',
    tags: ['汤类', '清甜', '营养'],
    imageUrl: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=冬瓜排骨汤美食照片，高清，诱人，中式汤品&image_size=portrait_4_3',
    tips: '冬瓜要后放，保持口感。',
    ingredients: [
      { name: '排骨', amount: '400g', category: '主料' },
      { name: '冬瓜', amount: '500g', category: '主料' },
      { name: '姜片', amount: '适量', category: '配料' },
      { name: '葱段', amount: '适量', category: '配料' },
      { name: '盐', amount: '适量', category: '调料' },
    ],
    steps: [
      { title: '焯水', content: '排骨冷水下锅焯水。' },
      { title: '炖排骨', content: '砂锅中加水，放入排骨、姜片炖30分钟。' },
      { title: '加冬瓜', content: '放入冬瓜块炖15分钟。' },
      { title: '调味', content: '加盐、葱段调味即可。' },
    ],
  },
  {
    id: 'recipe-xilan-hua-niurou',
    title: '西兰花炒牛肉',
    category: '下饭菜',
    difficulty: '简单',
    cookMinutes: 20,
    cookTime: '20分钟',
    description: '营养健康的经典搭配。牛肉嫩滑，西兰花脆嫩。',
    tags: ['下饭菜', '健康', '快手'],
    imageUrl: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=西兰花炒牛肉美食照片，高清，诱人，绿褐相间&image_size=portrait_4_3',
    tips: '牛肉要逆纹切，西兰花要焯水。',
    ingredients: [
      { name: '牛肉', amount: '250g', category: '主料' },
      { name: '西兰花', amount: '1颗', category: '主料' },
      { name: '蚝油', amount: '2勺', category: '调料' },
      { name: '生抽', amount: '1勺', category: '调料' },
      { name: '淀粉', amount: '适量', category: '调料' },
      { name: '姜蒜', amount: '适量', category: '配料' },
    ],
    steps: [
      { title: '腌制', content: '牛肉切片，加淀粉、生抽腌制。' },
      { title: '焯水', content: '西兰花切小朵，焯水备用。' },
      { title: '炒牛肉', content: '热锅下油，炒熟牛肉盛出。' },
      { title: '完成', content: '放入姜蒜、西兰花、牛肉、蚝油翻炒均匀。' },
    ],
  },
  {
    id: 'recipe-yangzhou-chaofan',
    title: '扬州炒饭',
    category: '快手菜',
    difficulty: '简单',
    cookMinutes: 15,
    cookTime: '15分钟',
    description: '经典炒饭，粒粒分明。配料丰富，色香味俱全。',
    tags: ['快手菜', '主食', '经典'],
    imageUrl: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=扬州炒饭美食照片，高清，诱人，色彩丰富&image_size=portrait_4_3',
    tips: '要用隔夜饭，配料要切小丁。',
    ingredients: [
      { name: '米饭', amount: '2碗', category: '主料' },
      { name: '鸡蛋', amount: '2个', category: '主料' },
      { name: '虾仁', amount: '50g', category: '配料' },
      { name: '火腿', amount: '适量', category: '配料' },
      { name: '豌豆', amount: '适量', category: '配料' },
      { name: '胡萝卜', amount: '适量', category: '配料' },
      { name: '葱花', amount: '适量', category: '配料' },
      { name: '盐', amount: '适量', category: '调料' },
    ],
    steps: [
      { title: '准备', content: '虾仁、火腿、胡萝卜切丁。' },
      { title: '炒蛋', content: '热锅下油，倒入蛋液炒散。' },
      { title: '炒配料', content: '放入虾仁、火腿、豌豆、胡萝卜丁翻炒。' },
      { title: '炒饭', content: '加入米饭大火翻炒均匀。' },
      { title: '调味', content: '加盐调味，撒葱花即可。' },
    ],
  },
  {
    id: 'recipe-hongshao-doufu',
    title: '红烧豆腐',
    category: '素菜',
    difficulty: '简单',
    cookMinutes: 15,
    cookTime: '15分钟',
    description: '外酥里嫩的经典素菜。豆腐金黄，酱香浓郁。',
    tags: ['素菜', '下饭菜', '经典'],
    imageUrl: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=红烧豆腐美食照片，高清，诱人，金黄&image_size=portrait_4_3',
    tips: '豆腐要选老豆腐，煎到两面金黄。',
    ingredients: [
      { name: '豆腐', amount: '1块', category: '主料' },
      { name: '生抽', amount: '2勺', category: '调料' },
      { name: '老抽', amount: '1勺', category: '调料' },
      { name: '白糖', amount: '1勺', category: '调料' },
      { name: '蒜末', amount: '适量', category: '配料' },
      { name: '淀粉', amount: '适量', category: '调料' },
    ],
    steps: [
      { title: '煎豆腐', content: '豆腐切块，锅中放油煎至两面金黄。' },
      { title: '调味', content: '加入蒜末、生抽、老抽、糖。' },
      { title: '炖煮', content: '加水炖5分钟，倒入水淀粉勾芡。' },
      { title: '完成', content: '大火收汁即可。' },
    ],
  },
  {
    id: 'recipe-shuizhuyu',
    title: '水煮鱼',
    category: '下饭菜',
    difficulty: '中等',
    cookMinutes: 30,
    cookTime: '30分钟',
    description: '麻辣鲜香的经典川菜。鱼片嫩滑，红油香辣。',
    tags: ['川菜', '下饭菜', '辣'],
    imageUrl: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=水煮鱼美食照片，高清，诱人，红油，中式菜肴&image_size=portrait_4_3',
    tips: '鱼片要薄，豆芽铺底。',
    ingredients: [
      { name: '草鱼', amount: '1条', category: '主料' },
      { name: '豆芽', amount: '200g', category: '配料' },
      { name: '干辣椒', amount: '适量', category: '配料' },
      { name: '花椒', amount: '适量', category: '调料' },
      { name: '豆瓣酱', amount: '2勺', category: '调料' },
      { name: '淀粉', amount: '适量', category: '调料' },
      { name: '料酒', amount: '2勺', category: '调料' },
    ],
    steps: [
      { title: '处理鱼', content: '草鱼去骨切片，加淀粉、料酒腌制。' },
      { title: '焯豆芽', content: '豆芽焯水铺在碗底。' },
      { title: '煮汤', content: '锅中放油，加入豆瓣酱炒出红油，加水烧开。' },
      { title: '下鱼片', content: '放入鱼片煮3分钟，倒在豆芽上。' },
      { title: '淋油', content: '撒上干辣椒、花椒，浇热油即可。' },
    ],
  },
  {
    id: 'recipe-zhengdangeng',
    title: '蒸蛋羹',
    category: '快手菜',
    difficulty: '简单',
    cookMinutes: 15,
    cookTime: '15分钟',
    description: '嫩滑可口的经典家常菜。蛋羹细腻，入口即化。',
    tags: ['快手菜', '经典', '简单'],
    imageUrl: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=蒸蛋羹美食照片，高清，诱人，嫩滑&image_size=portrait_4_3',
    tips: '蛋水比例1:1.5，过滤气泡更细腻。',
    ingredients: [
      { name: '鸡蛋', amount: '3个', category: '主料' },
      { name: '温水', amount: '适量', category: '调料' },
      { name: '生抽', amount: '1勺', category: '调料' },
      { name: '香油', amount: '适量', category: '调料' },
      { name: '葱花', amount: '适量', category: '配料' },
    ],
    steps: [
      { title: '打蛋', content: '鸡蛋打散，加入1.5倍温水。' },
      { title: '过滤', content: '过滤掉气泡。' },
      { title: '蒸制', content: '盖上保鲜膜，水开后蒸10分钟。' },
      { title: '调味', content: '淋生抽、香油，撒葱花即可。' },
    ],
  },
  {
    id: 'recipe-xianggu-chaoroupian',
    title: '香菇炒肉片',
    category: '下饭菜',
    difficulty: '简单',
    cookMinutes: 15,
    cookTime: '15分钟',
    description: '鲜香下饭的家常菜。香菇滑嫩，肉片香嫩。',
    tags: ['下饭菜', '快手菜'],
    imageUrl: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=香菇炒肉片美食照片，高清，诱人，中式炒菜&image_size=portrait_4_3',
    tips: '香菇要选鲜香菇，肉片要逆纹切。',
    ingredients: [
      { name: '猪里脊', amount: '200g', category: '主料' },
      { name: '鲜香菇', amount: '200g', category: '主料' },
      { name: '生抽', amount: '2勺', category: '调料' },
      { name: '蚝油', amount: '1勺', category: '调料' },
      { name: '淀粉', amount: '适量', category: '调料' },
      { name: '姜蒜', amount: '适量', category: '配料' },
    ],
    steps: [
      { title: '腌制', content: '猪里脊切片，加淀粉、生抽腌制。' },
      { title: '炒肉片', content: '热锅下油，炒熟肉片盛出。' },
      { title: '炒香菇', content: '放入姜蒜、香菇翻炒。' },
      { title: '完成', content: '倒入肉片，加蚝油、生抽翻炒均匀。' },
    ],
  },
  {
    id: 'recipe-kugua-paigu',
    title: '苦瓜排骨汤',
    category: '汤类',
    difficulty: '简单',
    cookMinutes: 50,
    cookTime: '50分钟',
    description: '清热解暑的经典汤品。苦瓜微苦，排骨鲜甜。',
    tags: ['汤类', '清热', '营养'],
    imageUrl: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=苦瓜排骨汤美食照片，高清，诱人，中式汤品&image_size=portrait_4_3',
    tips: '苦瓜去瓤去白膜减少苦味。',
    ingredients: [
      { name: '排骨', amount: '400g', category: '主料' },
      { name: '苦瓜', amount: '1根', category: '主料' },
      { name: '姜片', amount: '适量', category: '配料' },
      { name: '葱段', amount: '适量', category: '配料' },
      { name: '盐', amount: '适量', category: '调料' },
    ],
    steps: [
      { title: '焯水', content: '排骨冷水下锅焯水。' },
      { title: '炖排骨', content: '砂锅中加水，放入排骨、姜片炖30分钟。' },
      { title: '加苦瓜', content: '放入苦瓜块炖15分钟。' },
      { title: '调味', content: '加盐、葱段调味即可。' },
    ],
  },
  {
    id: 'recipe-yuxiang-qiezi',
    title: '鱼香茄子',
    category: '素菜',
    difficulty: '简单',
    cookMinutes: 20,
    cookTime: '20分钟',
    description: '酸甜辣香的经典素菜。茄子软糯，鱼香浓郁。',
    tags: ['素菜', '下饭菜', '川菜'],
    imageUrl: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=鱼香茄子美食照片，高清，诱人，红亮&image_size=portrait_4_3',
    tips: '茄子切块后撒盐腌制减少吸油。',
    ingredients: [
      { name: '茄子', amount: '2根', category: '主料' },
      { name: '猪肉末', amount: '50g', category: '配料' },
      { name: '白糖', amount: '2勺', category: '调料' },
      { name: '醋', amount: '2勺', category: '调料' },
      { name: '生抽', amount: '2勺', category: '调料' },
      { name: '豆瓣酱', amount: '1勺', category: '调料' },
      { name: '淀粉', amount: '适量', category: '调料' },
    ],
    steps: [
      { title: '准备', content: '茄子切块，撒盐腌制10分钟。' },
      { title: '调汁', content: '糖、醋、生抽、淀粉水混合成鱼香汁。' },
      { title: '炒肉末', content: '热锅下油，炒香肉末。' },
      { title: '炒茄子', content: '放入茄子翻炒至软糯。' },
      { title: '完成', content: '倒入鱼香汁、豆瓣酱翻炒均匀。' },
    ],
  },
  {
    id: 'recipe-huanggua-chaodan',
    title: '黄瓜炒鸡蛋',
    category: '素菜',
    difficulty: '简单',
    cookMinutes: 10,
    cookTime: '10分钟',
    description: '清爽简单的家常菜。黄瓜脆嫩，鸡蛋香滑。',
    tags: ['素菜', '快手菜', '简单'],
    imageUrl: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=黄瓜炒鸡蛋美食照片，高清，诱人，绿黄相间&image_size=portrait_4_3',
    tips: '黄瓜要最后放，保持脆嫩。',
    ingredients: [
      { name: '黄瓜', amount: '2根', category: '主料' },
      { name: '鸡蛋', amount: '3个', category: '主料' },
      { name: '盐', amount: '适量', category: '调料' },
      { name: '油', amount: '适量', category: '调料' },
    ],
    steps: [
      { title: '准备', content: '黄瓜切片，鸡蛋打散。' },
      { title: '炒蛋', content: '热锅下油，倒入蛋液炒熟盛出。' },
      { title: '炒黄瓜', content: '锅中放油，放入黄瓜快速翻炒。' },
      { title: '完成', content: '倒入鸡蛋，加盐翻炒均匀即可。' },
    ],
  },
  {
    id: 'recipe-hongshao-jizhua',
    title: '红烧鸡爪',
    category: '下饭菜',
    difficulty: '中等',
    cookMinutes: 45,
    cookTime: '45分钟',
    description: '软糯入味的经典小吃。鸡爪软烂，酱香浓郁。',
    tags: ['下饭菜', '小吃', '经典'],
    imageUrl: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=红烧鸡爪美食照片，高清，诱人，红亮&image_size=portrait_4_3',
    tips: '鸡爪要剪指甲，炸到起虎皮更入味。',
    ingredients: [
      { name: '鸡爪', amount: '500g', category: '主料' },
      { name: '生抽', amount: '3勺', category: '调料' },
      { name: '老抽', amount: '1勺', category: '调料' },
      { name: '冰糖', amount: '适量', category: '调料' },
      { name: '料酒', amount: '2勺', category: '调料' },
      { name: '姜片', amount: '适量', category: '配料' },
      { name: '八角', amount: '2个', category: '调料' },
    ],
    steps: [
      { title: '处理鸡爪', content: '鸡爪剪指甲，焯水备用。' },
      { title: '炸制', content: '锅中放油，炸鸡爪至起虎皮。' },
      { title: '调味', content: '加入姜片、八角、生抽、老抽、料酒、冰糖。' },
      { title: '炖煮', content: '加水炖30分钟，大火收汁即可。' },
    ],
  },
  {
    id: 'recipe-xiaren-xilanhua',
    title: '虾仁炒西兰花',
    category: '下饭菜',
    difficulty: '简单',
    cookMinutes: 15,
    cookTime: '15分钟',
    description: '营养健康的经典搭配。虾仁弹牙，西兰花脆嫩。',
    tags: ['下饭菜', '健康', '海鲜'],
    imageUrl: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=虾仁炒西兰花美食照片，高清，诱人，绿粉相间&image_size=portrait_4_3',
    tips: '虾仁要提前腌制，西兰花要焯水。',
    ingredients: [
      { name: '虾仁', amount: '300g', category: '主料' },
      { name: '西兰花', amount: '1颗', category: '主料' },
      { name: '蚝油', amount: '2勺', category: '调料' },
      { name: '生抽', amount: '1勺', category: '调料' },
      { name: '淀粉', amount: '适量', category: '调料' },
      { name: '姜蒜', amount: '适量', category: '配料' },
    ],
    steps: [
      { title: '腌制', content: '虾仁加淀粉、料酒腌制。' },
      { title: '焯水', content: '西兰花切小朵，焯水备用。' },
      { title: '炒虾仁', content: '热锅下油，炒熟虾仁盛出。' },
      { title: '完成', content: '放入姜蒜、西兰花、虾仁、蚝油翻炒均匀。' },
    ],
  },
  {
    id: 'recipe-yumi-paigu',
    title: '玉米排骨汤',
    category: '汤类',
    difficulty: '简单',
    cookMinutes: 60,
    cookTime: '1小时',
    description: '清甜营养的经典汤品。玉米甜糯，排骨软烂。',
    tags: ['汤类', '清甜', '营养'],
    imageUrl: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=玉米排骨汤美食照片，高清，诱人，中式汤品&image_size=portrait_4_3',
    tips: '玉米要选甜玉米，小火慢炖。',
    ingredients: [
      { name: '排骨', amount: '400g', category: '主料' },
      { name: '玉米', amount: '2根', category: '主料' },
      { name: '胡萝卜', amount: '1根', category: '配料' },
      { name: '姜片', amount: '适量', category: '配料' },
      { name: '葱段', amount: '适量', category: '配料' },
      { name: '盐', amount: '适量', category: '调料' },
    ],
    steps: [
      { title: '焯水', content: '排骨冷水下锅焯水。' },
      { title: '炖排骨', content: '砂锅中加水，放入排骨、姜片炖30分钟。' },
      { title: '加玉米', content: '放入玉米块、胡萝卜炖20分钟。' },
      { title: '调味', content: '加盐、葱段调味即可。' },
    ],
  },
  {
    id: 'recipe-mapodoufu',
    title: '麻婆豆腐',
    category: '下饭菜',
    difficulty: '简单',
    cookMinutes: 20,
    cookTime: '20分钟',
    description: '麻辣鲜香的经典川菜。豆腐嫩滑，肉末香浓。',
    tags: ['川菜', '下饭菜', '辣'],
    imageUrl: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=麻婆豆腐美食照片，高清，诱人，红油&image_size=portrait_4_3',
    tips: '豆腐要选嫩豆腐，勾芡分两次。',
    ingredients: [
      { name: '豆腐', amount: '1块', category: '主料' },
      { name: '猪肉末', amount: '100g', category: '主料' },
      { name: '豆瓣酱', amount: '2勺', category: '调料' },
      { name: '花椒粉', amount: '适量', category: '调料' },
      { name: '生抽', amount: '1勺', category: '调料' },
      { name: '淀粉', amount: '适量', category: '调料' },
      { name: '葱花', amount: '适量', category: '配料' },
    ],
    steps: [
      { title: '准备', content: '豆腐切块，焯水备用。' },
      { title: '炒肉末', content: '热锅下油，放入肉末炒至变色。' },
      { title: '调味', content: '加入豆瓣酱炒出红油，加生抽。' },
      { title: '烧豆腐', content: '放入豆腐块，加水烧5分钟。' },
      { title: '勾芡', content: '倒入水淀粉勾芡，撒花椒粉、葱花即可。' },
    ],
  },
  {
    id: 'recipe-basidigua',
    title: '拔丝地瓜',
    category: '素菜',
    difficulty: '困难',
    cookMinutes: 30,
    cookTime: '30分钟',
    description: '甜脆拉丝的经典甜品。地瓜软糯，糖丝晶莹。',
    tags: ['素菜', '甜品', '经典'],
    imageUrl: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=拔丝地瓜美食照片，高清，诱人，金黄，拉丝&image_size=portrait_4_3',
    tips: '炒糖色是关键，小火慢炒。',
    ingredients: [
      { name: '地瓜', amount: '400g', category: '主料' },
      { name: '白糖', amount: '100g', category: '调料' },
      { name: '油', amount: '适量', category: '调料' },
    ],
    steps: [
      { title: '准备', content: '地瓜去皮切块。' },
      { title: '炸制', content: '锅中放油，炸地瓜至金黄软糯。' },
      { title: '炒糖', content: '锅中留底油，小火炒化白糖至琥珀色。' },
      { title: '完成', content: '倒入地瓜快速翻炒裹上糖丝即可。' },
    ],
  },
];

async function main() {
  console.log(`开始导入 ${RECIPES.length} 道菜谱...\n`);
  
  let successCount = 0;
  let skipCount = 0;
  
  for (const recipe of RECIPES) {
    const existing = await query('SELECT id FROM recipes WHERE id = ?', [recipe.id]);
    if (existing.length > 0) {
      console.log(`跳过（已存在）: ${recipe.title}`);
      skipCount++;
      continue;
    }
    
    await query(
      `INSERT INTO recipes (id, title, category, difficulty, cookMinutes, cookTime, description, tags, imageUrl, tips, sourceType) 
       VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 'seed')`,
      [recipe.id, recipe.title, recipe.category, recipe.difficulty, recipe.cookMinutes, recipe.cookTime, 
       recipe.description, JSON.stringify(recipe.tags), recipe.imageUrl, recipe.tips]
    );
    
    for (const ing of recipe.ingredients) {
      await query(
        'INSERT INTO ingredients (id, recipeId, name, amount, category) VALUES (?, ?, ?, ?, ?)',
        [uuidv4(), recipe.id, ing.name, ing.amount, ing.category]
      );
    }
    
    for (let i = 0; i < recipe.steps.length; i++) {
      await query(
        'INSERT INTO steps (id, recipeId, orderNum, title, content) VALUES (?, ?, ?, ?, ?)',
        [uuidv4(), recipe.id, i + 1, recipe.steps[i].title, recipe.steps[i].content]
      );
    }
    
    successCount++;
    console.log(`已添加 (${successCount}/${RECIPES.length}): ${recipe.title}`);
  }
  
  console.log(`\n导入完成!`);
  console.log(`成功添加: ${successCount} 道菜谱`);
  console.log(`跳过: ${skipCount} 道`);
  
  const total = await query('SELECT COUNT(*) as total FROM recipes');
  console.log(`数据库中共有: ${total[0].total} 道菜谱`);
  
  await db.end();
}

main().catch(console.error);