import { query } from './db.js';

export async function initDatabase() {
  try {
    await query(`
      CREATE TABLE IF NOT EXISTS recipes (
        id VARCHAR(36) PRIMARY KEY,
        familyId VARCHAR(36) DEFAULT 'default',
        title VARCHAR(128) NOT NULL,
        category VARCHAR(32),
        difficulty VARCHAR(16) DEFAULT '简单',
        cookMinutes INT,
        cookTime VARCHAR(16),
        description TEXT,
        tags TEXT,
        imageUrl VARCHAR(512),
        sourceType VARCHAR(16) DEFAULT 'custom',
        tips TEXT,
        createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
        updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
      ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
    `);

    await query(`
      CREATE TABLE IF NOT EXISTS ingredients (
        id VARCHAR(36) PRIMARY KEY,
        recipeId VARCHAR(36) NOT NULL,
        name VARCHAR(64) NOT NULL,
        amount VARCHAR(32),
        category VARCHAR(32),
        FOREIGN KEY (recipeId) REFERENCES recipes(id) ON DELETE CASCADE
      ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
    `);

    await query(`
      CREATE TABLE IF NOT EXISTS steps (
        id VARCHAR(36) PRIMARY KEY,
        recipeId VARCHAR(36) NOT NULL,
        orderNum INT NOT NULL,
        title VARCHAR(64),
        content TEXT NOT NULL,
        FOREIGN KEY (recipeId) REFERENCES recipes(id) ON DELETE CASCADE,
        UNIQUE KEY uk_recipe_order (recipeId, orderNum)
      ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
    `);

    await query(`
      CREATE TABLE IF NOT EXISTS mealPicks (
        id VARCHAR(36) PRIMARY KEY,
        familyId VARCHAR(36) DEFAULT 'default',
        recipeId VARCHAR(36) NOT NULL,
        recipeTitle VARCHAR(128),
        status VARCHAR(16) DEFAULT 'active',
        pickedDate DATE NOT NULL,
        FOREIGN KEY (recipeId) REFERENCES recipes(id) ON DELETE CASCADE,
        UNIQUE KEY uk_family_recipe_date (familyId, recipeId, pickedDate)
      ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
    `);

    await query(`
      CREATE TABLE IF NOT EXISTS shoppingList (
        id VARCHAR(36) PRIMARY KEY,
        familyId VARCHAR(36) DEFAULT 'default',
        name VARCHAR(64) NOT NULL,
        amountText VARCHAR(32),
        checked TINYINT(1) DEFAULT 0,
        recipeTitles TEXT,
        createdAt DATETIME DEFAULT CURRENT_TIMESTAMP
      ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
    `);

    await query(`
      CREATE TABLE IF NOT EXISTS purchases (
        id VARCHAR(36) PRIMARY KEY,
        familyId VARCHAR(36) DEFAULT 'default',
        storeName VARCHAR(64),
        purchaseDate DATE NOT NULL,
        purchaseTime VARCHAR(8),
        totalAmount DECIMAL(10,2) DEFAULT 0,
        sourceType VARCHAR(16) DEFAULT 'manual',
        note VARCHAR(256),
        createdAt DATETIME DEFAULT CURRENT_TIMESTAMP
      ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
    `);

    await query(`
      CREATE TABLE IF NOT EXISTS purchaseItems (
        id VARCHAR(36) PRIMARY KEY,
        purchaseId VARCHAR(36) NOT NULL,
        name VARCHAR(64) NOT NULL,
        quantity DECIMAL(10,2) DEFAULT 1,
        price DECIMAL(10,2) DEFAULT 0,
        amountText VARCHAR(32),
        FOREIGN KEY (purchaseId) REFERENCES purchases(id) ON DELETE CASCADE
      ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
    `);

    await query(`
      CREATE TABLE IF NOT EXISTS favorites (
        id VARCHAR(36) PRIMARY KEY,
        familyId VARCHAR(36) DEFAULT 'default',
        recipeId VARCHAR(36) NOT NULL,
        recipeTitle VARCHAR(128),
        createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY (recipeId) REFERENCES recipes(id) ON DELETE CASCADE,
        UNIQUE KEY uk_family_recipe (familyId, recipeId)
      ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
    `);

    const count = await query('SELECT COUNT(*) as count FROM recipes');
    if (count[0].count === 0) {
      await insertSampleData();
    }

    console.log('数据库初始化完成');
  } catch (error) {
    console.error('数据库初始化失败:', error);
    throw error;
  }
}

async function insertSampleData() {
  const recipes = [
    {
      id: 'recipe-tomato-egg',
      title: '番茄炒蛋',
      category: '快手菜',
      difficulty: '简单',
      cookMinutes: 15,
      cookTime: '15分钟',
      description: '经典家常菜，简单易做，营养丰富。酸甜开胃，十几分钟就能上桌。',
      tags: JSON.stringify(['家常', '快手', '下饭菜']),
      imageUrl: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=番茄炒蛋%20中式家常菜%20红色番茄%20金黄鸡蛋%20热气腾腾&image_size=square',
      tips: '番茄要选熟透的，炒出来更香甜。番茄先炒出汁，味道更浓。'
    },
    {
      id: 'recipe-sour-potato',
      title: '酸辣土豆丝',
      category: '快手菜',
      difficulty: '简单',
      cookMinutes: 18,
      cookTime: '18分钟',
      description: '爽脆开胃，搭米饭特别稳。酸辣适中，口感爽脆。',
      tags: JSON.stringify(['快手菜', '素菜', '下饭菜', '酸辣']),
      imageUrl: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=酸辣土豆丝%20中式家常菜%20金黄土豆丝%20酸辣爽口https://images.unsplash.com/photo-1512058564366-18510be2db19?w=800image_size=square',
      tips: '土豆丝切细一点更脆，泡水去淀粉口感更好。'
    },
    {
      id: 'recipe-corn-rib-soup',
      title: '玉米排骨汤',
      category: '汤类',
      difficulty: '简单',
      cookMinutes: 60,
      cookTime: '60分钟',
      description: '清甜暖胃，适合全家一起喝。营养丰富，汤鲜味美。',
      tags: JSON.stringify(['汤类', '营养', '清淡']),
      imageUrl: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=中式汤品%20清甜暖胃%20营养丰富https://images.unsplash.com/photo-1547592166-23ac45744acd?w=800image_size=square',
      tips: '排骨提前焯水去腥，汤更清爽。小火慢炖，汤更浓郁。'
    },
    {
      id: 'recipe-braised-pork',
      title: '红烧肉',
      category: '下饭菜',
      difficulty: '中等',
      cookMinutes: 50,
      cookTime: '50分钟',
      description: '肥而不腻，入口即化。经典中式菜肴，适合周末认真做一顿。',
      tags: JSON.stringify(['硬菜', '下饭菜', '经典']),
      imageUrl: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=红烧肉%20中式经典菜肴%20色泽红亮%20肥而不腻https://images.unsplash.com/photo-1605522561233-768ad7a8fabf?w=800image_size=square',
      tips: '糖色不要炒过头，小火慢炖肉质更软烂。'
    },
    {
      id: 'recipe-broccoli',
      title: '蒜蓉西兰花',
      category: '素菜',
      difficulty: '简单',
      cookMinutes: 10,
      cookTime: '10分钟',
      description: '清爽轻盈，用来搭配肉菜很舒服。蒜香浓郁，营养丰富。',
      tags: JSON.stringify(['素菜', '快手菜', '健康']),
      imageUrl: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=蒜蓉西兰花%20绿色蔬菜%20清爽健康https://images.unsplash.com/photo-1540420773420-3366772f4999?w=800image_size=square',
      tips: '焯水时加一点油和盐，能保持颜色鲜绿。'
    },
    {
      id: 'recipe-chicken-cola',
      title: '可乐鸡翅',
      category: '下饭菜',
      difficulty: '简单',
      cookMinutes: 30,
      cookTime: '30分钟',
      description: '甜香可口，简单易做。色泽红亮，口感嫩滑。',
      tags: JSON.stringify(['快手', '下饭菜', '甜香']),
      imageUrl: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=可乐鸡翅%20中式家常菜%20色泽红亮%20甜香可口https://images.unsplash.com/photo-1527476053921-3d444b4c93d2?w=800image_size=square',
      tips: '可乐要倒完，不要加水。大火收汁让鸡翅更入味。'
    },
    {
      id: 'recipe-green-vegetables',
      title: '清炒时蔬',
      category: '素菜',
      difficulty: '简单',
      cookMinutes: 10,
      cookTime: '10分钟',
      description: '清爽健康的素菜，保留蔬菜原味。简单快手，营养健康。',
      tags: JSON.stringify(['素菜', '健康', '快手']),
      imageUrl: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=清炒时蔬%20绿色蔬菜%20清爽健康https://images.unsplash.com/photo-1512058564366-613b367f3a62?w=800image_size=square',
      tips: '大火快炒，保持蔬菜脆嫩。不要炒太久，保持营养。'
    },
    {
      id: 'recipe-tomato-beef',
      title: '番茄牛腩汤',
      category: '汤类',
      difficulty: '中等',
      cookMinutes: 90,
      cookTime: '1.5小时',
      description: '酸甜可口的汤品，营养丰富。汤鲜味美，肉质软烂。',
      tags: JSON.stringify(['汤类', '营养', '酸甜']),
      imageUrl: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=中式汤品%20清甜暖胃%20营养丰富https://images.unsplash.com/photo-1547592166-23ac45744acd?w=800image_size=square',
      tips: '牛腩要先焯水去腥，小火慢炖肉质更软烂。'
    },
    {
      id: 'recipe-egg-drop-soup',
      title: '紫菜蛋花汤',
      category: '汤类',
      difficulty: '简单',
      cookMinutes: 10,
      cookTime: '10分钟',
      description: '简单快手的营养汤品。清淡鲜美，适合搭配各种菜肴。',
      tags: JSON.stringify(['汤类', '快手', '营养']),
      imageUrl: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=中式汤品%20清甜暖胃%20营养丰富https://images.unsplash.com/photo-1547592166-23ac45744acd?w=800image_size=square',
      tips: '蛋液要慢慢倒入，形成漂亮的蛋花。'
    },
    {
      id: 'recipe-fried-rice',
      title: '蛋炒饭',
      category: '快手菜',
      difficulty: '简单',
      cookMinutes: 15,
      cookTime: '15分钟',
      description: '简单快手的主食，粒粒分明。金黄诱人，香气扑鼻。',
      tags: JSON.stringify(['快手', '主食', '简单']),
      imageUrl: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=蛋炒饭%20金黄米饭%20粒粒分明https://images.unsplash.com/photo-1603133872875-674d6b3b9b8f?w=800image_size=square',
      tips: '米饭要用隔夜饭，炒出来更干爽。大火快炒，粒粒分明。'
    },
    {
      id: 'recipe-kung-pao-chicken',
      title: '宫保鸡丁',
      category: '下饭菜',
      difficulty: '中等',
      cookMinutes: 25,
      cookTime: '25分钟',
      description: '经典川菜，鸡肉嫩滑，花生香脆。麻辣鲜香，下饭神器。',
      tags: JSON.stringify(['川菜', '下饭菜', '经典']),
      imageUrl: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=可乐鸡翅%20中式家常菜%20色泽红亮%20甜香可口https://images.unsplash.com/photo-1527476053921-3d444b4c93d2?w=800image_size=square',
      tips: '鸡肉要提前腌制入味，花生最后放保持脆感。'
    },
    {
      id: 'recipe-mapo-tofu',
      title: '麻婆豆腐',
      category: '下饭菜',
      difficulty: '简单',
      cookMinutes: 20,
      cookTime: '20分钟',
      description: '麻辣鲜香的经典川菜。豆腐嫩滑，肉末香脆。',
      tags: JSON.stringify(['川菜', '下饭菜', '豆腐']),
      imageUrl: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=麻婆豆腐%20川菜经典%20麻辣鲜香https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800image_size=square',
      tips: '豆腐要选嫩豆腐，口感更好。花椒粉最后撒。'
    },
    {
      id: 'recipe-sweet-sour-ribs',
      title: '糖醋排骨',
      category: '下饭菜',
      difficulty: '中等',
      cookMinutes: 40,
      cookTime: '40分钟',
      description: '酸甜可口的经典菜肴。色泽红亮，外酥里嫩。',
      tags: JSON.stringify(['经典', '下饭菜', '酸甜']),
      imageUrl: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=糖醋排骨%20中式经典菜肴%20色泽红亮%20酸甜可口https://images.unsplash.com/photo-1544025162-d76694265947?w=800image_size=square',
      tips: '糖醋比例要掌握好，一般3:4:2:1。'
    },
    {
      id: 'recipe-yuxiang-pork',
      title: '鱼香肉丝',
      category: '下饭菜',
      difficulty: '中等',
      cookMinutes: 25,
      cookTime: '25分钟',
      description: '酸甜辣香的经典川菜。肉丝嫩滑，配菜爽脆。',
      tags: JSON.stringify(['川菜', '下饭菜', '经典']),
      imageUrl: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=可乐鸡翅%20中式家常菜%20色泽红亮%20甜香可口https://images.unsplash.com/photo-1527476053921-3d444b4c93d2?w=800image_size=square',
      tips: '肉丝要顺着纹理切，腌制时加淀粉更嫩。'
    },
    {
      id: 'recipe-twice-cooked-pork',
      title: '回锅肉',
      category: '下饭菜',
      difficulty: '中等',
      cookMinutes: 30,
      cookTime: '30分钟',
      description: '川菜经典，肥而不腻。肉片卷曲，蒜苗清香。',
      tags: JSON.stringify(['川菜', '下饭菜', '经典']),
      imageUrl: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=糖醋排骨%20中式经典菜肴%20色泽红亮%20酸甜可口https://images.unsplash.com/photo-1544025162-d76694265947?w=800image_size=square',
      tips: '肉要煮到筷子能扎透，切片要薄。'
    },
    {
      id: 'recipe-dry-beans',
      title: '干煸四季豆',
      category: '素菜',
      difficulty: '简单',
      cookMinutes: 20,
      cookTime: '20分钟',
      description: '干香爽口的经典素菜。四季豆起皱，肉末香脆。',
      tags: JSON.stringify(['素菜', '下饭菜', '经典']),
      imageUrl: 'https://images.unsplash.com/photo-1512058564366-613b367d3a62?w=800',
      tips: '四季豆要煸炒至表皮起皱，确保熟透。'
    },
    {
      id: 'recipe-steamed-fish',
      title: '清蒸鲈鱼',
      category: '下饭菜',
      difficulty: '中等',
      cookMinutes: 20,
      cookTime: '20分钟',
      description: '鲜嫩清淡的经典蒸菜。鱼肉细嫩，原汁原味。',
      tags: JSON.stringify(['蒸菜', '清淡', '经典']),
      imageUrl: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=麻婆豆腐%20川菜经典%20麻辣鲜香https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800image_size=square',
      tips: '蒸的时间要掌握好，一般10-12分钟。'
    },
    {
      id: 'recipe-braised-eggplant',
      title: '红烧茄子',
      category: '素菜',
      difficulty: '简单',
      cookMinutes: 20,
      cookTime: '20分钟',
      description: '软糯入味的经典素菜。茄子吸汁，蒜香浓郁。',
      tags: JSON.stringify(['素菜', '下饭菜', '经典']),
      imageUrl: 'https://images.unsplash.com/photo-1512058564366-613b367d3a62?w=800',
      tips: '茄子切块后撒盐腌制可以防止吸油。'
    },
    {
      id: 'recipe-tomato-noodle',
      title: '西红柿鸡蛋面',
      category: '快手菜',
      difficulty: '简单',
      cookMinutes: 15,
      cookTime: '15分钟',
      description: '简单快捷的营养面食。汤鲜面滑，酸甜开胃。',
      tags: JSON.stringify(['快手', '面食', '家常']),
      imageUrl: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=麻婆豆腐%20川菜经典%20麻辣鲜香https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800image_size=square',
      tips: '面条要煮到刚好断生，不要过软。'
    },
    {
      id: 'recipe-scallion-noodle',
      title: '葱油拌面',
      category: '快手菜',
      difficulty: '简单',
      cookMinutes: 15,
      cookTime: '15分钟',
      description: '简单美味的经典面食。葱香浓郁，面条爽滑。',
      tags: JSON.stringify(['快手', '面食', '经典']),
      imageUrl: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=麻婆豆腐%20川菜经典%20麻辣鲜香https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800image_size=square',
      tips: '葱油要小火慢熬，葱段焦黄即可。'
    },
    {
      id: 'recipe-green-pepper-pork',
      title: '青椒肉丝',
      category: '快手菜',
      difficulty: '简单',
      cookMinutes: 15,
      cookTime: '15分钟',
      description: '简单快捷的经典家常菜。肉丝嫩滑，青椒爽脆。',
      tags: JSON.stringify(['快手', '下饭菜', '家常']),
      imageUrl: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=可乐鸡翅%20中式家常菜%20色泽红亮%20甜香可口https://images.unsplash.com/photo-1527476053921-3d444b4c93d2?w=800image_size=square',
      tips: '肉丝要提前腌制，大火快炒保持嫩滑。'
    },
    {
      id: 'recipe-oyster-lettuce',
      title: '蚝油生菜',
      category: '素菜',
      difficulty: '简单',
      cookMinutes: 10,
      cookTime: '10分钟',
      description: '清爽简单的素菜。生菜脆嫩，蚝油鲜香。',
      tags: JSON.stringify(['素菜', '快手', '清淡']),
      imageUrl: 'https://images.unsplash.com/photo-1512058564366-613b367d3a62?w=800',
      tips: '生菜焯水时间要短，保持脆嫩。'
    },
    {
      id: 'recipe-hot-sour-soup',
      title: '酸辣汤',
      category: '汤类',
      difficulty: '简单',
      cookMinutes: 15,
      cookTime: '15分钟',
      description: '酸辣开胃的经典汤品。汤浓味美，暖胃驱寒。',
      tags: JSON.stringify(['汤类', '酸辣', '经典']),
      imageUrl: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=中式汤品%20清甜暖胃%20营养丰富https://images.unsplash.com/photo-1547592166-23ac45744acd?w=800image_size=square',
      tips: '醋要最后放，保持酸味。胡椒粉适量。'
    },
    {
      id: 'recipe-winter-melon-soup',
      title: '冬瓜排骨汤',
      category: '汤类',
      difficulty: '简单',
      cookMinutes: 60,
      cookTime: '1小时',
      description: '清淡营养的经典汤品。冬瓜透明，排骨软烂。',
      tags: JSON.stringify(['汤类', '清淡', '营养']),
      imageUrl: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=中式汤品%20清甜暖胃%20营养丰富https://images.unsplash.com/photo-1547592166-23ac45744acd?w=800image_size=square',
      tips: '排骨要先焯水去腥，小火慢炖。'
    },
    {
      id: 'recipe-cola-ribs',
      title: '可乐排骨',
      category: '下饭菜',
      difficulty: '简单',
      cookMinutes: 35,
      cookTime: '35分钟',
      description: '甜香可口的排骨做法。色泽红亮，肉质软嫩。',
      tags: JSON.stringify(['快手', '下饭菜', '甜香']),
      imageUrl: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=糖醋排骨%20中式经典菜肴%20色泽红亮%20酸甜可口https://images.unsplash.com/photo-1544025162-d76694265947?w=800image_size=square',
      tips: '可乐要倒完，不要加水。大火收汁更入味。'
    },
    {
      id: 'recipe-steamed-shrimp',
      title: '蒜蓉粉丝蒸虾',
      category: '下饭菜',
      difficulty: '中等',
      cookMinutes: 20,
      cookTime: '20分钟',
      description: '鲜美可口的蒸菜。虾肉弹牙，粉丝吸汁。',
      tags: JSON.stringify(['蒸菜', '海鲜', '经典']),
      imageUrl: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=麻婆豆腐%20川菜经典%20麻辣鲜香https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800image_size=square',
      tips: '虾要开背去虾线，粉丝泡软铺底。'
    },
    {
      id: 'recipe-dry-pot-cauliflower',
      title: '干锅花菜',
      category: '素菜',
      difficulty: '简单',
      cookMinutes: 20,
      cookTime: '20分钟',
      description: '干香爽口的经典素菜。花菜微焦，五花肉香。',
      tags: JSON.stringify(['素菜', '下饭菜', '经典']),
      imageUrl: 'https://images.unsplash.com/photo-1512058564366-613b367d3a62?w=800',
      tips: '花菜要煸炒至微焦，口感更好。'
    },
    {
      id: 'recipe-three-fresh',
      title: '地三鲜',
      category: '素菜',
      difficulty: '中等',
      cookMinutes: 25,
      cookTime: '25分钟',
      description: '东北经典素菜，软糯鲜香。土豆茄子青椒，绝配。',
      tags: JSON.stringify(['素菜', '下饭菜', '东北菜']),
      imageUrl: 'https://images.unsplash.com/photo-1512058564366-613b367d3a62?w=800',
      tips: '土豆、茄子、青椒都要炸过，再一起炒。'
    },
    {
      id: 'recipe-mu-shu-pork',
      title: '木须肉',
      category: '下饭菜',
      difficulty: '简单',
      cookMinutes: 20,
      cookTime: '20分钟',
      description: '经典家常菜，营养丰富。鸡蛋肉片木耳，色彩丰富。',
      tags: JSON.stringify(['家常', '下饭菜', '经典']),
      imageUrl: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=可乐鸡翅%20中式家常菜%20色泽红亮%20甜香可口https://images.unsplash.com/photo-1527476053921-3d444b4c93d2?w=800image_size=square',
      tips: '肉片要提前腌制，鸡蛋炒熟后盛出。'
    },
    {
      id: 'recipe-boiled-fish',
      title: '水煮鱼',
      category: '下饭菜',
      difficulty: '中等',
      cookMinutes: 30,
      cookTime: '30分钟',
      description: '麻辣鲜香的经典川菜。鱼片嫩滑，豆芽爽脆。',
      tags: JSON.stringify(['川菜', '下饭菜', '经典']),
      imageUrl: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=糖醋排骨%20中式经典菜肴%20色泽红亮%20酸甜可口https://images.unsplash.com/photo-1544025162-d76694265947?w=800image_size=square',
      tips: '鱼片要薄，煮的时间要短，保持嫩滑。'
    },
    {
      id: 'recipe-sour-fish',
      title: '酸菜鱼',
      category: '汤类',
      difficulty: '中等',
      cookMinutes: 30,
      cookTime: '30分钟',
      description: '酸爽开胃的经典川菜。鱼片嫩滑，酸菜鲜香。',
      tags: JSON.stringify(['川菜', '汤类', '经典']),
      imageUrl: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=中式汤品%20清甜暖胃%20营养丰富https://images.unsplash.com/photo-1547592166-23ac45744acd?w=800image_size=square',
      tips: '酸菜要提前泡水去咸味，鱼片加淀粉腌制。'
    },
    {
      id: 'recipe-braised-hairtail',
      title: '红烧带鱼',
      category: '下饭菜',
      difficulty: '简单',
      cookMinutes: 25,
      cookTime: '25分钟',
      description: '鲜香入味的经典鱼菜。带鱼外酥里嫩，汤汁浓郁。',
      tags: JSON.stringify(['下饭菜', '海鲜', '经典']),
      imageUrl: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=麻婆豆腐%20川菜经典%20麻辣鲜香https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800image_size=square',
      tips: '带鱼要先煎至两面金黄，再红烧。'
    },
    {
      id: 'recipe-sweet-sour-loin',
      title: '糖醋里脊',
      category: '下饭菜',
      difficulty: '中等',
      cookMinutes: 30,
      cookTime: '30分钟',
      description: '酸甜可口的经典菜肴。外酥里嫩，色泽红亮。',
      tags: JSON.stringify(['下饭菜', '酸甜', '经典']),
      imageUrl: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=糖醋排骨%20中式经典菜肴%20色泽红亮%20酸甜可口https://images.unsplash.com/photo-1544025162-d76694265947?w=800image_size=square',
      tips: '里脊肉要切均匀，挂糊要薄。'
    },
    {
      id: 'recipe-yuxiang-eggplant',
      title: '鱼香茄子',
      category: '素菜',
      difficulty: '简单',
      cookMinutes: 20,
      cookTime: '20分钟',
      description: '酸甜辣香的经典素菜。茄子软糯，肉末香脆。',
      tags: JSON.stringify(['素菜', '下饭菜', '经典']),
      imageUrl: 'https://images.unsplash.com/photo-1512058564366-613b367d3a62?w=800',
      tips: '茄子切条后撒盐腌制，防止吸油。'
    },
    {
      id: 'recipe-garlic-pork',
      title: '蒜泥白肉',
      category: '下饭菜',
      difficulty: '中等',
      cookMinutes: 30,
      cookTime: '30分钟',
      description: '蒜香浓郁的经典川菜。肉片薄嫩，蒜泥香辣。',
      tags: JSON.stringify(['川菜', '下饭菜', '经典']),
      imageUrl: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=糖醋排骨%20中式经典菜肴%20色泽红亮%20酸甜可口https://images.unsplash.com/photo-1544025162-d76694265947?w=800image_size=square',
      tips: '肉要煮到筷子能扎透，切片要薄。'
    },
    {
      id: 'recipe-dry-beef',
      title: '干煸牛肉丝',
      category: '下饭菜',
      difficulty: '中等',
      cookMinutes: 30,
      cookTime: '30分钟',
      description: '干香有嚼劲的经典菜肴。牛肉丝干香，辣椒花椒香。',
      tags: JSON.stringify(['下饭菜', '经典', '牛肉']),
      imageUrl: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=糖醋排骨%20中式经典菜肴%20色泽红亮%20酸甜可口https://images.unsplash.com/photo-1544025162-d76694265947?w=800image_size=square',
      tips: '牛肉要顺着纹理切丝，煸炒至干香。'
    },
    {
      id: 'recipe-scallion-lamb',
      title: '葱爆羊肉',
      category: '下饭菜',
      difficulty: '简单',
      cookMinutes: 15,
      cookTime: '15分钟',
      description: '葱香浓郁的快手羊肉菜。羊肉嫩滑，大葱清香。',
      tags: JSON.stringify(['快手', '下饭菜', '羊肉']),
      imageUrl: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=糖醋排骨%20中式经典菜肴%20色泽红亮%20酸甜可口https://images.unsplash.com/photo-1544025162-d76694265947?w=800image_size=square',
      tips: '羊肉要切薄片，大火快炒。'
    },
    {
      id: 'recipe-kung-pao-shrimp',
      title: '宫保虾球',
      category: '下饭菜',
      difficulty: '中等',
      cookMinutes: 20,
      cookTime: '20分钟',
      description: '虾肉弹牙，花生香脆。麻辣鲜香，下饭神器。',
      tags: JSON.stringify(['下饭菜', '海鲜', '快手']),
      imageUrl: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=可乐鸡翅%20中式家常菜%20色泽红亮%20甜香可口https://images.unsplash.com/photo-1527476053921-3d444b4c93d2?w=800image_size=square',
      tips: '虾要去虾线，加料酒腌制。'
    },
    {
      id: 'recipe-steamed-luffa',
      title: '蒜蓉蒸丝瓜',
      category: '素菜',
      difficulty: '简单',
      cookMinutes: 15,
      cookTime: '15分钟',
      description: '清淡爽口的蒸菜。丝瓜嫩滑，蒜香浓郁。',
      tags: JSON.stringify(['素菜', '蒸菜', '清淡']),
      imageUrl: 'https://images.unsplash.com/photo-1512058564366-613b367d3a62?w=800',
      tips: '丝瓜要选嫩的，蒸的时间不要过长。'
    },
    {
      id: 'recipe-oyster-beef',
      title: '蚝油牛肉',
      category: '下饭菜',
      difficulty: '中等',
      cookMinutes: 20,
      cookTime: '20分钟',
      description: '牛肉嫩滑，蚝油鲜香。经典粤菜，下饭神器。',
      tags: JSON.stringify(['下饭菜', '牛肉', '经典']),
      imageUrl: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=糖醋排骨%20中式经典菜肴%20色泽红亮%20酸甜可口https://images.unsplash.com/photo-1544025162-d76694265947?w=800image_size=square',
      tips: '牛肉要逆纹切，腌制时加淀粉。'
    },
    {
      id: 'recipe-braised-tofu',
      title: '红烧豆腐',
      category: '素菜',
      difficulty: '简单',
      cookMinutes: 15,
      cookTime: '15分钟',
      description: '外焦里嫩的经典素菜。豆腐吸汁，蒜香浓郁。',
      tags: JSON.stringify(['素菜', '下饭菜', '豆腐']),
      imageUrl: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=麻婆豆腐%20川菜经典%20麻辣鲜香https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800image_size=square',
      tips: '豆腐要煎至两面金黄，再红烧。'
    },
    {
      id: 'recipe-dry-pot-potato',
      title: '干锅土豆片',
      category: '素菜',
      difficulty: '简单',
      cookMinutes: 20,
      cookTime: '20分钟',
      description: '外焦里糯的经典素菜。土豆片香脆，五花肉香。',
      tags: JSON.stringify(['素菜', '下饭菜', '经典']),
      imageUrl: 'https://images.unsplash.com/photo-1512058564366-613b367d3a62?w=800',
      tips: '土豆片要切均匀，煎至两面金黄。'
    },
    {
      id: 'recipe-roasted-eggplant',
      title: '蒜蓉烤茄子',
      category: '素菜',
      difficulty: '简单',
      cookMinutes: 25,
      cookTime: '25分钟',
      description: '蒜香浓郁的烤茄子。茄子软糯，蒜蓉香辣。',
      tags: JSON.stringify(['素菜', '烤菜', '经典']),
      imageUrl: 'https://images.unsplash.com/photo-1512058564366-613b367d3a62?w=800',
      tips: '茄子要选长的，烤至软烂。'
    },
    {
      id: 'recipe-tomato-egg-soup',
      title: '番茄蛋汤',
      category: '汤类',
      difficulty: '简单',
      cookMinutes: 10,
      cookTime: '10分钟',
      description: '酸甜开胃的经典汤品。番茄鲜红，蛋花漂亮。',
      tags: JSON.stringify(['汤类', '快手', '经典']),
      imageUrl: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=中式汤品%20清甜暖胃%20营养丰富https://images.unsplash.com/photo-1547592166-23ac45744acd?w=800image_size=square',
      tips: '番茄要炒出汁再加水，蛋液慢慢倒。'
    },
    {
      id: 'recipe-lotus-root-soup',
      title: '莲藕排骨汤',
      category: '汤类',
      difficulty: '简单',
      cookMinutes: 60,
      cookTime: '1小时',
      description: '清甜粉糯的经典汤品。莲藕粉糯，排骨软烂。',
      tags: JSON.stringify(['汤类', '清甜', '营养']),
      imageUrl: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=中式汤品%20清甜暖胃%20营养丰富https://images.unsplash.com/photo-1547592166-23ac45744acd?w=800image_size=square',
      tips: '莲藕要选粉藕，小火慢炖。'
    },
    {
      id: 'recipe-radish-beef',
      title: '萝卜牛腩煲',
      category: '下饭菜',
      difficulty: '中等',
      cookMinutes: 90,
      cookTime: '1.5小时',
      description: '软烂入味的经典煲菜。牛腩软烂，萝卜清甜。',
      tags: JSON.stringify(['下饭菜', '经典', '煲菜']),
      imageUrl: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=糖醋排骨%20中式经典菜肴%20色泽红亮%20酸甜可口https://images.unsplash.com/photo-1544025162-d76694265947?w=800image_size=square',
      tips: '牛腩要选带筋的，小火慢炖。'
    },
    {
      id: 'recipe-plum-pork',
      title: '梅菜扣肉',
      category: '下饭菜',
      difficulty: '困难',
      cookMinutes: 120,
      cookTime: '2小时',
      description: '经典粤菜，肥而不腻。梅菜香浓，肉片软烂。',
      tags: JSON.stringify(['粤菜', '下饭菜', '经典']),
      imageUrl: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=糖醋排骨%20中式经典菜肴%20色泽红亮%20酸甜可口https://images.unsplash.com/photo-1544025162-d76694265947?w=800image_size=square',
      tips: '肉要煮到筷子能扎透，蒸的时间要够。'
    },
    {
      id: 'recipe-dongpo-pork',
      title: '东坡肉',
      category: '下饭菜',
      difficulty: '困难',
      cookMinutes: 120,
      cookTime: '2小时',
      description: '经典杭帮菜，入口即化。肉片方正，色泽红亮。',
      tags: JSON.stringify(['杭帮菜', '下饭菜', '经典']),
      imageUrl: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=糖醋排骨%20中式经典菜肴%20色泽红亮%20酸甜可口https://images.unsplash.com/photo-1544025162-d76694265947?w=800image_size=square',
      tips: '小火慢炖是关键，黄酒要多放。'
    },
    {
      id: 'recipe-mouth-water-chicken',
      title: '口水鸡',
      category: '下饭菜',
      difficulty: '中等',
      cookMinutes: 30,
      cookTime: '30分钟',
      description: '麻辣鲜香的经典凉菜。鸡肉嫩滑，红油香辣。',
      tags: JSON.stringify(['川菜', '凉菜', '经典']),
      imageUrl: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=可乐鸡翅%20中式家常菜%20色泽红亮%20甜香可口https://images.unsplash.com/photo-1527476053921-3d444b4c93d2?w=800image_size=square',
      tips: '鸡要煮到刚熟，过冰水更嫩。'
    }
  ];

  for (const recipe of recipes) {
    await query(
      'INSERT INTO recipes (id, title, category, difficulty, cookMinutes, cookTime, description, tags, imageUrl, tips) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)',
      [recipe.id, recipe.title, recipe.category, recipe.difficulty, recipe.cookMinutes, recipe.cookTime, recipe.description, recipe.tags, recipe.imageUrl, recipe.tips]
    );
  }

  const ingredients = [
    { recipeId: 'recipe-tomato-egg', name: '番茄', amount: '2个', category: '主料' },
    { recipeId: 'recipe-tomato-egg', name: '鸡蛋', amount: '3个', category: '主料' },
    { recipeId: 'recipe-tomato-egg', name: '葱花', amount: '适量', category: '配料' },
    { recipeId: 'recipe-tomato-egg', name: '盐', amount: '适量', category: '调料' },
    { recipeId: 'recipe-tomato-egg', name: '糖', amount: '少许', category: '调料' },
    { recipeId: 'recipe-sour-potato', name: '土豆', amount: '2个', category: '主料' },
    { recipeId: 'recipe-sour-potato', name: '干辣椒', amount: '适量', category: '配料' },
    { recipeId: 'recipe-sour-potato', name: '醋', amount: '2勺', category: '调料' },
    { recipeId: 'recipe-sour-potato', name: '盐', amount: '适量', category: '调料' },
    { recipeId: 'recipe-sour-potato', name: '葱花', amount: '适量', category: '配料' },
    { recipeId: 'recipe-corn-rib-soup', name: '排骨', amount: '500g', category: '主料' },
    { recipeId: 'recipe-corn-rib-soup', name: '玉米', amount: '1根', category: '主料' },
    { recipeId: 'recipe-corn-rib-soup', name: '胡萝卜', amount: '1根', category: '主料' },
    { recipeId: 'recipe-corn-rib-soup', name: '姜片', amount: '3片', category: '配料' },
    { recipeId: 'recipe-braised-pork', name: '五花肉', amount: '500g', category: '主料' },
    { recipeId: 'recipe-braised-pork', name: '冰糖', amount: '30g', category: '调料' },
    { recipeId: 'recipe-braised-pork', name: '生抽', amount: '2勺', category: '调料' },
    { recipeId: 'recipe-braised-pork', name: '老抽', amount: '1勺', category: '调料' },
    { recipeId: 'recipe-braised-pork', name: '八角', amount: '2个', category: '香料' },
    { recipeId: 'recipe-braised-pork', name: '桂皮', amount: '1小块', category: '香料' },
    { recipeId: 'recipe-broccoli', name: '西兰花', amount: '1颗', category: '主料' },
    { recipeId: 'recipe-broccoli', name: '蒜', amount: '4瓣', category: '配料' },
    { recipeId: 'recipe-broccoli', name: '盐', amount: '适量', category: '调料' },
    { recipeId: 'recipe-broccoli', name: '油', amount: '适量', category: '调料' },
    { recipeId: 'recipe-chicken-cola', name: '鸡翅', amount: '8个', category: '主料' },
    { recipeId: 'recipe-chicken-cola', name: '可乐', amount: '1罐', category: '调料' },
    { recipeId: 'recipe-chicken-cola', name: '生抽', amount: '2勺', category: '调料' },
    { recipeId: 'recipe-chicken-cola', name: '老抽', amount: '1勺', category: '调料' },
    { recipeId: 'recipe-chicken-cola', name: '姜片', amount: '适量', category: '配料' },
    { recipeId: 'recipe-green-vegetables', name: '青菜', amount: '300g', category: '主料' },
    { recipeId: 'recipe-green-vegetables', name: '蒜末', amount: '适量', category: '配料' },
    { recipeId: 'recipe-green-vegetables', name: '盐', amount: '适量', category: '调料' },
    { recipeId: 'recipe-green-vegetables', name: '油', amount: '适量', category: '调料' },
    { recipeId: 'recipe-tomato-beef', name: '牛腩', amount: '500g', category: '主料' },
    { recipeId: 'recipe-tomato-beef', name: '番茄', amount: '3个', category: '主料' },
    { recipeId: 'recipe-tomato-beef', name: '土豆', amount: '1个', category: '主料' },
    { recipeId: 'recipe-tomato-beef', name: '番茄酱', amount: '2勺', category: '调料' },
    { recipeId: 'recipe-tomato-beef', name: '盐', amount: '适量', category: '调料' },
    { recipeId: 'recipe-egg-drop-soup', name: '紫菜', amount: '适量', category: '主料' },
    { recipeId: 'recipe-egg-drop-soup', name: '鸡蛋', amount: '1个', category: '主料' },
    { recipeId: 'recipe-egg-drop-soup', name: '盐', amount: '适量', category: '调料' },
    { recipeId: 'recipe-egg-drop-soup', name: '香油', amount: '少许', category: '调料' },
    { recipeId: 'recipe-fried-rice', name: '米饭', amount: '1碗', category: '主料' },
    { recipeId: 'recipe-fried-rice', name: '鸡蛋', amount: '2个', category: '主料' },
    { recipeId: 'recipe-fried-rice', name: '葱花', amount: '适量', category: '配料' },
    { recipeId: 'recipe-fried-rice', name: '盐', amount: '适量', category: '调料' },
    { recipeId: 'recipe-fried-rice', name: '油', amount: '适量', category: '调料' },
    { recipeId: 'recipe-kung-pao-chicken', name: '鸡胸肉', amount: '300g', category: '主料' },
    { recipeId: 'recipe-kung-pao-chicken', name: '花生米', amount: '50g', category: '配料' },
    { recipeId: 'recipe-kung-pao-chicken', name: '干辣椒', amount: '适量', category: '配料' },
    { recipeId: 'recipe-kung-pao-chicken', name: '花椒', amount: '适量', category: '调料' },
    { recipeId: 'recipe-kung-pao-chicken', name: '黄瓜', amount: '1根', category: '配料' },
    { recipeId: 'recipe-kung-pao-chicken', name: '生抽', amount: '2勺', category: '调料' },
    { recipeId: 'recipe-kung-pao-chicken', name: '料酒', amount: '1勺', category: '调料' },
    { recipeId: 'recipe-kung-pao-chicken', name: '醋', amount: '1勺', category: '调料' },
    { recipeId: 'recipe-kung-pao-chicken', name: '糖', amount: '1勺', category: '调料' },
    { recipeId: 'recipe-mapo-tofu', name: '豆腐', amount: '1块', category: '主料' },
    { recipeId: 'recipe-mapo-tofu', name: '猪肉末', amount: '100g', category: '主料' },
    { recipeId: 'recipe-mapo-tofu', name: '豆瓣酱', amount: '2勺', category: '调料' },
    { recipeId: 'recipe-mapo-tofu', name: '花椒粉', amount: '适量', category: '调料' },
    { recipeId: 'recipe-mapo-tofu', name: '葱花', amount: '适量', category: '配料' },
    { recipeId: 'recipe-mapo-tofu', name: '姜末', amount: '适量', category: '配料' },
    { recipeId: 'recipe-mapo-tofu', name: '蒜末', amount: '适量', category: '配料' },
    { recipeId: 'recipe-sweet-sour-ribs', name: '排骨', amount: '500g', category: '主料' },
    { recipeId: 'recipe-sweet-sour-ribs', name: '白糖', amount: '3勺', category: '调料' },
    { recipeId: 'recipe-sweet-sour-ribs', name: '醋', amount: '4勺', category: '调料' },
    { recipeId: 'recipe-sweet-sour-ribs', name: '生抽', amount: '2勺', category: '调料' },
    { recipeId: 'recipe-sweet-sour-ribs', name: '料酒', amount: '1勺', category: '调料' },
    { recipeId: 'recipe-sweet-sour-ribs', name: '姜片', amount: '适量', category: '配料' },
    { recipeId: 'recipe-sweet-sour-ribs', name: '葱段', amount: '适量', category: '配料' },
    { recipeId: 'recipe-yuxiang-pork', name: '猪里脊', amount: '300g', category: '主料' },
    { recipeId: 'recipe-yuxiang-pork', name: '木耳', amount: '适量', category: '配料' },
    { recipeId: 'recipe-yuxiang-pork', name: '胡萝卜', amount: '1根', category: '配料' },
    { recipeId: 'recipe-yuxiang-pork', name: '青椒', amount: '1个', category: '配料' },
    { recipeId: 'recipe-yuxiang-pork', name: '豆瓣酱', amount: '2勺', category: '调料' },
    { recipeId: 'recipe-yuxiang-pork', name: '醋', amount: '2勺', category: '调料' },
    { recipeId: 'recipe-yuxiang-pork', name: '糖', amount: '2勺', category: '调料' },
    { recipeId: 'recipe-yuxiang-pork', name: '生抽', amount: '1勺', category: '调料' },
    { recipeId: 'recipe-twice-cooked-pork', name: '五花肉', amount: '400g', category: '主料' },
    { recipeId: 'recipe-twice-cooked-pork', name: '青蒜', amount: '适量', category: '配料' },
    { recipeId: 'recipe-twice-cooked-pork', name: '豆瓣酱', amount: '2勺', category: '调料' },
    { recipeId: 'recipe-twice-cooked-pork', name: '甜面酱', amount: '1勺', category: '调料' },
    { recipeId: 'recipe-twice-cooked-pork', name: '姜片', amount: '适量', category: '配料' },
    { recipeId: 'recipe-twice-cooked-pork', name: '料酒', amount: '2勺', category: '调料' },
    { recipeId: 'recipe-dry-beans', name: '四季豆', amount: '400g', category: '主料' },
    { recipeId: 'recipe-dry-beans', name: '猪肉末', amount: '50g', category: '主料' },
    { recipeId: 'recipe-dry-beans', name: '干辣椒', amount: '适量', category: '配料' },
    { recipeId: 'recipe-dry-beans', name: '蒜末', amount: '适量', category: '配料' },
    { recipeId: 'recipe-dry-beans', name: '盐', amount: '适量', category: '调料' },
    { recipeId: 'recipe-dry-beans', name: '生抽', amount: '1勺', category: '调料' },
    { recipeId: 'recipe-steamed-fish', name: '鲈鱼', amount: '1条', category: '主料' },
    { recipeId: 'recipe-steamed-fish', name: '葱段', amount: '适量', category: '配料' },
    { recipeId: 'recipe-steamed-fish', name: '姜片', amount: '适量', category: '配料' },
    { recipeId: 'recipe-steamed-fish', name: '蒸鱼豉油', amount: '3勺', category: '调料' },
    { recipeId: 'recipe-steamed-fish', name: '料酒', amount: '2勺', category: '调料' },
    { recipeId: 'recipe-steamed-fish', name: '葱丝', amount: '适量', category: '配料' },
    { recipeId: 'recipe-braised-eggplant', name: '茄子', amount: '3根', category: '主料' },
    { recipeId: 'recipe-braised-eggplant', name: '蒜末', amount: '适量', category: '配料' },
    { recipeId: 'recipe-braised-eggplant', name: '生抽', amount: '2勺', category: '调料' },
    { recipeId: 'recipe-braised-eggplant', name: '老抽', amount: '1勺', category: '调料' },
    { recipeId: 'recipe-braised-eggplant', name: '白糖', amount: '1勺', category: '调料' },
    { recipeId: 'recipe-braised-eggplant', name: '淀粉', amount: '适量', category: '调料' },
    { recipeId: 'recipe-tomato-noodle', name: '面条', amount: '200g', category: '主料' },
    { recipeId: 'recipe-tomato-noodle', name: '番茄', amount: '2个', category: '主料' },
    { recipeId: 'recipe-tomato-noodle', name: '鸡蛋', amount: '2个', category: '主料' },
    { recipeId: 'recipe-tomato-noodle', name: '葱花', amount: '适量', category: '配料' },
    { recipeId: 'recipe-tomato-noodle', name: '盐', amount: '适量', category: '调料' },
    { recipeId: 'recipe-tomato-noodle', name: '生抽', amount: '1勺', category: '调料' },
    { recipeId: 'recipe-scallion-noodle', name: '面条', amount: '200g', category: '主料' },
    { recipeId: 'recipe-scallion-noodle', name: '葱', amount: '适量', category: '配料' },
    { recipeId: 'recipe-scallion-noodle', name: '生抽', amount: '3勺', category: '调料' },
    { recipeId: 'recipe-scallion-noodle', name: '老抽', amount: '1勺', category: '调料' },
    { recipeId: 'recipe-scallion-noodle', name: '白糖', amount: '1勺', category: '调料' },
    { recipeId: 'recipe-scallion-noodle', name: '油', amount: '适量', category: '调料' },
    { recipeId: 'recipe-green-pepper-pork', name: '猪里脊', amount: '200g', category: '主料' },
    { recipeId: 'recipe-green-pepper-pork', name: '青椒', amount: '3个', category: '主料' },
    { recipeId: 'recipe-green-pepper-pork', name: '生抽', amount: '2勺', category: '调料' },
    { recipeId: 'recipe-green-pepper-pork', name: '料酒', amount: '1勺', category: '调料' },
    { recipeId: 'recipe-green-pepper-pork', name: '淀粉', amount: '适量', category: '调料' },
    { recipeId: 'recipe-green-pepper-pork', name: '盐', amount: '适量', category: '调料' },
    { recipeId: 'recipe-oyster-lettuce', name: '生菜', amount: '400g', category: '主料' },
    { recipeId: 'recipe-oyster-lettuce', name: '蚝油', amount: '2勺', category: '调料' },
    { recipeId: 'recipe-oyster-lettuce', name: '蒜末', amount: '适量', category: '配料' },
    { recipeId: 'recipe-oyster-lettuce', name: '生抽', amount: '1勺', category: '调料' },
    { recipeId: 'recipe-oyster-lettuce', name: '淀粉', amount: '适量', category: '调料' },
    { recipeId: 'recipe-hot-sour-soup', name: '豆腐', amount: '1块', category: '主料' },
    { recipeId: 'recipe-hot-sour-soup', name: '木耳', amount: '适量', category: '配料' },
    { recipeId: 'recipe-hot-sour-soup', name: '香菇', amount: '适量', category: '配料' },
    { recipeId: 'recipe-hot-sour-soup', name: '鸡蛋', amount: '1个', category: '主料' },
    { recipeId: 'recipe-hot-sour-soup', name: '醋', amount: '3勺', category: '调料' },
    { recipeId: 'recipe-hot-sour-soup', name: '胡椒粉', amount: '适量', category: '调料' },
    { recipeId: 'recipe-hot-sour-soup', name: '淀粉', amount: '适量', category: '调料' },
    { recipeId: 'recipe-winter-melon-soup', name: '排骨', amount: '500g', category: '主料' },
    { recipeId: 'recipe-winter-melon-soup', name: '冬瓜', amount: '500g', category: '主料' },
    { recipeId: 'recipe-winter-melon-soup', name: '姜片', amount: '适量', category: '配料' },
    { recipeId: 'recipe-winter-melon-soup', name: '葱段', amount: '适量', category: '配料' },
    { recipeId: 'recipe-winter-melon-soup', name: '料酒', amount: '2勺', category: '调料' },
    { recipeId: 'recipe-winter-melon-soup', name: '盐', amount: '适量', category: '调料' },
    { recipeId: 'recipe-cola-ribs', name: '排骨', amount: '500g', category: '主料' },
    { recipeId: 'recipe-cola-ribs', name: '可乐', amount: '1罐', category: '调料' },
    { recipeId: 'recipe-cola-ribs', name: '生抽', amount: '2勺', category: '调料' },
    { recipeId: 'recipe-cola-ribs', name: '老抽', amount: '1勺', category: '调料' },
    { recipeId: 'recipe-cola-ribs', name: '姜片', amount: '适量', category: '配料' },
    { recipeId: 'recipe-steamed-shrimp', name: '虾', amount: '500g', category: '主料' },
    { recipeId: 'recipe-steamed-shrimp', name: '粉丝', amount: '1把', category: '配料' },
    { recipeId: 'recipe-steamed-shrimp', name: '蒜末', amount: '适量', category: '配料' },
    { recipeId: 'recipe-steamed-shrimp', name: '生抽', amount: '2勺', category: '调料' },
    { recipeId: 'recipe-steamed-shrimp', name: '蚝油', amount: '1勺', category: '调料' },
    { recipeId: 'recipe-steamed-shrimp', name: '葱花', amount: '适量', category: '配料' },
    { recipeId: 'recipe-dry-pot-cauliflower', name: '花菜', amount: '1颗', category: '主料' },
    { recipeId: 'recipe-dry-pot-cauliflower', name: '五花肉', amount: '50g', category: '主料' },
    { recipeId: 'recipe-dry-pot-cauliflower', name: '干辣椒', amount: '适量', category: '配料' },
    { recipeId: 'recipe-dry-pot-cauliflower', name: '蒜片', amount: '适量', category: '配料' },
    { recipeId: 'recipe-dry-pot-cauliflower', name: '生抽', amount: '2勺', category: '调料' },
    { recipeId: 'recipe-dry-pot-cauliflower', name: '蚝油', amount: '1勺', category: '调料' },
    { recipeId: 'recipe-three-fresh', name: '土豆', amount: '2个', category: '主料' },
    { recipeId: 'recipe-three-fresh', name: '茄子', amount: '1个', category: '主料' },
    { recipeId: 'recipe-three-fresh', name: '青椒', amount: '1个', category: '主料' },
    { recipeId: 'recipe-three-fresh', name: '生抽', amount: '2勺', category: '调料' },
    { recipeId: 'recipe-three-fresh', name: '白糖', amount: '1勺', category: '调料' },
    { recipeId: 'recipe-three-fresh', name: '淀粉', amount: '适量', category: '调料' },
    { recipeId: 'recipe-mu-shu-pork', name: '猪里脊', amount: '200g', category: '主料' },
    { recipeId: 'recipe-mu-shu-pork', name: '鸡蛋', amount: '2个', category: '主料' },
    { recipeId: 'recipe-mu-shu-pork', name: '木耳', amount: '适量', category: '配料' },
    { recipeId: 'recipe-mu-shu-pork', name: '黄瓜', amount: '1根', category: '配料' },
    { recipeId: 'recipe-mu-shu-pork', name: '胡萝卜', amount: '适量', category: '配料' },
    { recipeId: 'recipe-mu-shu-pork', name: '生抽', amount: '2勺', category: '调料' },
    { recipeId: 'recipe-mu-shu-pork', name: '盐', amount: '适量', category: '调料' },
    { recipeId: 'recipe-boiled-fish', name: '草鱼', amount: '1条', category: '主料' },
    { recipeId: 'recipe-boiled-fish', name: '豆芽', amount: '适量', category: '配料' },
    { recipeId: 'recipe-boiled-fish', name: '豆瓣酱', amount: '3勺', category: '调料' },
    { recipeId: 'recipe-boiled-fish', name: '干辣椒', amount: '适量', category: '配料' },
    { recipeId: 'recipe-boiled-fish', name: '花椒', amount: '适量', category: '调料' },
    { recipeId: 'recipe-boiled-fish', name: '淀粉', amount: '适量', category: '调料' },
    { recipeId: 'recipe-boiled-fish', name: '蛋清', amount: '1个', category: '调料' },
    { recipeId: 'recipe-sour-fish', name: '草鱼', amount: '1条', category: '主料' },
    { recipeId: 'recipe-sour-fish', name: '酸菜', amount: '200g', category: '主料' },
    { recipeId: 'recipe-sour-fish', name: '泡椒', amount: '适量', category: '配料' },
    { recipeId: 'recipe-sour-fish', name: '姜片', amount: '适量', category: '配料' },
    { recipeId: 'recipe-sour-fish', name: '蒜片', amount: '适量', category: '配料' },
    { recipeId: 'recipe-sour-fish', name: '淀粉', amount: '适量', category: '调料' },
    { recipeId: 'recipe-sour-fish', name: '蛋清', amount: '1个', category: '调料' },
    { recipeId: 'recipe-braised-hairtail', name: '带鱼', amount: '500g', category: '主料' },
    { recipeId: 'recipe-braised-hairtail', name: '姜片', amount: '适量', category: '配料' },
    { recipeId: 'recipe-braised-hairtail', name: '葱段', amount: '适量', category: '配料' },
    { recipeId: 'recipe-braised-hairtail', name: '生抽', amount: '2勺', category: '调料' },
    { recipeId: 'recipe-braised-hairtail', name: '老抽', amount: '1勺', category: '调料' },
    { recipeId: 'recipe-braised-hairtail', name: '料酒', amount: '2勺', category: '调料' },
    { recipeId: 'recipe-braised-hairtail', name: '白糖', amount: '1勺', category: '调料' },
    { recipeId: 'recipe-sweet-sour-loin', name: '猪里脊', amount: '400g', category: '主料' },
    { recipeId: 'recipe-sweet-sour-loin', name: '白糖', amount: '3勺', category: '调料' },
    { recipeId: 'recipe-sweet-sour-loin', name: '醋', amount: '4勺', category: '调料' },
    { recipeId: 'recipe-sweet-sour-loin', name: '番茄酱', amount: '3勺', category: '调料' },
    { recipeId: 'recipe-sweet-sour-loin', name: '淀粉', amount: '适量', category: '调料' },
    { recipeId: 'recipe-sweet-sour-loin', name: '鸡蛋', amount: '1个', category: '调料' },
    { recipeId: 'recipe-sweet-sour-loin', name: '盐', amount: '适量', category: '调料' },
    { recipeId: 'recipe-yuxiang-eggplant', name: '茄子', amount: '3根', category: '主料' },
    { recipeId: 'recipe-yuxiang-eggplant', name: '猪肉末', amount: '50g', category: '主料' },
    { recipeId: 'recipe-yuxiang-eggplant', name: '豆瓣酱', amount: '2勺', category: '调料' },
    { recipeId: 'recipe-yuxiang-eggplant', name: '醋', amount: '2勺', category: '调料' },
    { recipeId: 'recipe-yuxiang-eggplant', name: '糖', amount: '2勺', category: '调料' },
    { recipeId: 'recipe-yuxiang-eggplant', name: '生抽', amount: '1勺', category: '调料' },
    { recipeId: 'recipe-yuxiang-eggplant', name: '蒜末', amount: '适量', category: '配料' },
    { recipeId: 'recipe-garlic-pork', name: '五花肉', amount: '400g', category: '主料' },
    { recipeId: 'recipe-garlic-pork', name: '蒜末', amount: '适量', category: '配料' },
    { recipeId: 'recipe-garlic-pork', name: '辣椒油', amount: '2勺', category: '调料' },
    { recipeId: 'recipe-garlic-pork', name: '生抽', amount: '3勺', category: '调料' },
    { recipeId: 'recipe-garlic-pork', name: '醋', amount: '1勺', category: '调料' },
    { recipeId: 'recipe-garlic-pork', name: '白糖', amount: '1勺', category: '调料' },
    { recipeId: 'recipe-dry-beef', name: '牛肉', amount: '400g', category: '主料' },
    { recipeId: 'recipe-dry-beef', name: '干辣椒', amount: '适量', category: '配料' },
    { recipeId: 'recipe-dry-beef', name: '花椒', amount: '适量', category: '调料' },
    { recipeId: 'recipe-dry-beef', name: '姜丝', amount: '适量', category: '配料' },
    { recipeId: 'recipe-dry-beef', name: '蒜丝', amount: '适量', category: '配料' },
    { recipeId: 'recipe-dry-beef', name: '生抽', amount: '2勺', category: '调料' },
    { recipeId: 'recipe-dry-beef', name: '料酒', amount: '1勺', category: '调料' },
    { recipeId: 'recipe-scallion-lamb', name: '羊肉', amount: '300g', category: '主料' },
    { recipeId: 'recipe-scallion-lamb', name: '大葱', amount: '2根', category: '配料' },
    { recipeId: 'recipe-scallion-lamb', name: '生抽', amount: '2勺', category: '调料' },
    { recipeId: 'recipe-scallion-lamb', name: '料酒', amount: '1勺', category: '调料' },
    { recipeId: 'recipe-scallion-lamb', name: '盐', amount: '适量', category: '调料' },
    { recipeId: 'recipe-scallion-lamb', name: '胡椒粉', amount: '适量', category: '调料' },
    { recipeId: 'recipe-kung-pao-shrimp', name: '虾', amount: '400g', category: '主料' },
    { recipeId: 'recipe-kung-pao-shrimp', name: '花生米', amount: '50g', category: '配料' },
    { recipeId: 'recipe-kung-pao-shrimp', name: '干辣椒', amount: '适量', category: '配料' },
    { recipeId: 'recipe-kung-pao-shrimp', name: '花椒', amount: '适量', category: '调料' },
    { recipeId: 'recipe-kung-pao-shrimp', name: '黄瓜', amount: '1根', category: '配料' },
    { recipeId: 'recipe-kung-pao-shrimp', name: '生抽', amount: '2勺', category: '调料' },
    { recipeId: 'recipe-kung-pao-shrimp', name: '醋', amount: '1勺', category: '调料' },
    { recipeId: 'recipe-kung-pao-shrimp', name: '糖', amount: '1勺', category: '调料' },
    { recipeId: 'recipe-steamed-luffa', name: '丝瓜', amount: '2根', category: '主料' },
    { recipeId: 'recipe-steamed-luffa', name: '蒜末', amount: '适量', category: '配料' },
    { recipeId: 'recipe-steamed-luffa', name: '生抽', amount: '2勺', category: '调料' },
    { recipeId: 'recipe-steamed-luffa', name: '盐', amount: '适量', category: '调料' },
    { recipeId: 'recipe-steamed-luffa', name: '油', amount: '适量', category: '调料' },
    { recipeId: 'recipe-oyster-beef', name: '牛肉', amount: '300g', category: '主料' },
    { recipeId: 'recipe-oyster-beef', name: '蚝油', amount: '3勺', category: '调料' },
    { recipeId: 'recipe-oyster-beef', name: '生抽', amount: '2勺', category: '调料' },
    { recipeId: 'recipe-oyster-beef', name: '淀粉', amount: '适量', category: '调料' },
    { recipeId: 'recipe-oyster-beef', name: '姜蒜', amount: '适量', category: '配料' },
    { recipeId: 'recipe-oyster-beef', name: '青椒', amount: '2个', category: '配料' },
    { recipeId: 'recipe-braised-tofu', name: '豆腐', amount: '1块', category: '主料' },
    { recipeId: 'recipe-braised-tofu', name: '生抽', amount: '2勺', category: '调料' },
    { recipeId: 'recipe-braised-tofu', name: '老抽', amount: '1勺', category: '调料' },
    { recipeId: 'recipe-braised-tofu', name: '白糖', amount: '1勺', category: '调料' },
    { recipeId: 'recipe-braised-tofu', name: '蒜末', amount: '适量', category: '配料' },
    { recipeId: 'recipe-braised-tofu', name: '淀粉', amount: '适量', category: '调料' },
    { recipeId: 'recipe-dry-pot-potato', name: '土豆', amount: '3个', category: '主料' },
    { recipeId: 'recipe-dry-pot-potato', name: '五花肉', amount: '50g', category: '主料' },
    { recipeId: 'recipe-dry-pot-potato', name: '干辣椒', amount: '适量', category: '配料' },
    { recipeId: 'recipe-dry-pot-potato', name: '花椒', amount: '适量', category: '调料' },
    { recipeId: 'recipe-dry-pot-potato', name: '蒜片', amount: '适量', category: '配料' },
    { recipeId: 'recipe-dry-pot-potato', name: '生抽', amount: '2勺', category: '调料' },
    { recipeId: 'recipe-roasted-eggplant', name: '茄子', amount: '3根', category: '主料' },
    { recipeId: 'recipe-roasted-eggplant', name: '蒜末', amount: '适量', category: '配料' },
    { recipeId: 'recipe-roasted-eggplant', name: '生抽', amount: '3勺', category: '调料' },
    { recipeId: 'recipe-roasted-eggplant', name: '蚝油', amount: '1勺', category: '调料' },
    { recipeId: 'recipe-roasted-eggplant', name: '葱花', amount: '适量', category: '配料' },
    { recipeId: 'recipe-tomato-egg-soup', name: '番茄', amount: '2个', category: '主料' },
    { recipeId: 'recipe-tomato-egg-soup', name: '鸡蛋', amount: '2个', category: '主料' },
    { recipeId: 'recipe-tomato-egg-soup', name: '葱花', amount: '适量', category: '配料' },
    { recipeId: 'recipe-tomato-egg-soup', name: '盐', amount: '适量', category: '调料' },
    { recipeId: 'recipe-tomato-egg-soup', name: '糖', amount: '少许', category: '调料' },
    { recipeId: 'recipe-lotus-root-soup', name: '排骨', amount: '500g', category: '主料' },
    { recipeId: 'recipe-lotus-root-soup', name: '莲藕', amount: '2节', category: '主料' },
    { recipeId: 'recipe-lotus-root-soup', name: '姜片', amount: '适量', category: '配料' },
    { recipeId: 'recipe-lotus-root-soup', name: '葱段', amount: '适量', category: '配料' },
    { recipeId: 'recipe-lotus-root-soup', name: '盐', amount: '适量', category: '调料' },
    { recipeId: 'recipe-radish-beef', name: '牛腩', amount: '500g', category: '主料' },
    { recipeId: 'recipe-radish-beef', name: '白萝卜', amount: '1根', category: '主料' },
    { recipeId: 'recipe-radish-beef', name: '生抽', amount: '3勺', category: '调料' },
    { recipeId: 'recipe-radish-beef', name: '老抽', amount: '1勺', category: '调料' },
    { recipeId: 'recipe-radish-beef', name: '料酒', amount: '2勺', category: '调料' },
    { recipeId: 'recipe-radish-beef', name: '八角', amount: '2个', category: '香料' },
    { recipeId: 'recipe-radish-beef', name: '桂皮', amount: '1小块', category: '香料' },
    { recipeId: 'recipe-plum-pork', name: '五花肉', amount: '500g', category: '主料' },
    { recipeId: 'recipe-plum-pork', name: '梅菜', amount: '100g', category: '配料' },
    { recipeId: 'recipe-plum-pork', name: '生抽', amount: '2勺', category: '调料' },
    { recipeId: 'recipe-plum-pork', name: '老抽', amount: '1勺', category: '调料' },
    { recipeId: 'recipe-plum-pork', name: '料酒', amount: '2勺', category: '调料' },
    { recipeId: 'recipe-plum-pork', name: '白糖', amount: '1勺', category: '调料' },
    { recipeId: 'recipe-dongpo-pork', name: '五花肉', amount: '500g', category: '主料' },
    { recipeId: 'recipe-dongpo-pork', name: '黄酒', amount: '200ml', category: '调料' },
    { recipeId: 'recipe-dongpo-pork', name: '生抽', amount: '3勺', category: '调料' },
    { recipeId: 'recipe-dongpo-pork', name: '老抽', amount: '1勺', category: '调料' },
    { recipeId: 'recipe-dongpo-pork', name: '冰糖', amount: '适量', category: '调料' },
    { recipeId: 'recipe-dongpo-pork', name: '姜片', amount: '适量', category: '配料' },
    { recipeId: 'recipe-dongpo-pork', name: '葱段', amount: '适量', category: '配料' },
    { recipeId: 'recipe-mouth-water-chicken', name: '鸡腿', amount: '2个', category: '主料' },
    { recipeId: 'recipe-mouth-water-chicken', name: '辣椒油', amount: '3勺', category: '调料' },
    { recipeId: 'recipe-mouth-water-chicken', name: '生抽', amount: '3勺', category: '调料' },
    { recipeId: 'recipe-mouth-water-chicken', name: '醋', amount: '1勺', category: '调料' },
    { recipeId: 'recipe-mouth-water-chicken', name: '花椒粉', amount: '适量', category: '调料' },
    { recipeId: 'recipe-mouth-water-chicken', name: '花生碎', amount: '适量', category: '配料' },
    { recipeId: 'recipe-mouth-water-chicken', name: '葱花', amount: '适量', category: '配料' }
  ];

  for (const ing of ingredients) {
    await query(
      'INSERT INTO ingredients (id, recipeId, name, amount, category) VALUES (UUID(), ?, ?, ?, ?)',
      [ing.recipeId, ing.name, ing.amount, ing.category]
    );
  }

  const steps = [
    { recipeId: 'recipe-tomato-egg', orderNum: 1, title: '准备食材', content: '番茄切块，鸡蛋打散备用。' },
    { recipeId: 'recipe-tomato-egg', orderNum: 2, title: '炒鸡蛋', content: '热锅下油，倒入蛋液炒至凝固盛出。' },
    { recipeId: 'recipe-tomato-egg', orderNum: 3, title: '炒番茄', content: '锅中放油，放入番茄翻炒至出汁。' },
    { recipeId: 'recipe-tomato-egg', orderNum: 4, title: '调味', content: '加入盐和少许糖调味。' },
    { recipeId: 'recipe-tomato-egg', orderNum: 5, title: '完成', content: '倒入炒好的鸡蛋，翻炒均匀即可。' },
    { recipeId: 'recipe-sour-potato', orderNum: 1, title: '切丝', content: '土豆切丝后泡水10分钟去淀粉。' },
    { recipeId: 'recipe-sour-potato', orderNum: 2, title: '爆香', content: '热锅下油，放入干辣椒爆香。' },
    { recipeId: 'recipe-sour-potato', orderNum: 3, title: '炒土豆', content: '放入土豆丝大火快炒。' },
    { recipeId: 'recipe-sour-potato', orderNum: 4, title: '调味', content: '加醋和盐调味。' },
    { recipeId: 'recipe-sour-potato', orderNum: 5, title: '完成', content: '撒上葱花即可出锅。' },
    { recipeId: 'recipe-corn-rib-soup', orderNum: 1, title: '焯水', content: '排骨冷水下锅焯水去腥。' },
    { recipeId: 'recipe-corn-rib-soup', orderNum: 2, title: '炖煮', content: '排骨加水炖45分钟至软烂。' },
    { recipeId: 'recipe-corn-rib-soup', orderNum: 3, title: '加配菜', content: '放入玉米和胡萝卜继续炖15分钟。' },
    { recipeId: 'recipe-corn-rib-soup', orderNum: 4, title: '调味', content: '加盐调味即可。' },
    { recipeId: 'recipe-braised-pork', orderNum: 1, title: '切块焯水', content: '五花肉切块，冷水下锅焯水。' },
    { recipeId: 'recipe-braised-pork', orderNum: 2, title: '炒糖色', content: '锅中放油和冰糖，炒至焦糖色。' },
    { recipeId: 'recipe-braised-pork', orderNum: 3, title: '炒肉', content: '放入肉块翻炒上色。' },
    { recipeId: 'recipe-braised-pork', orderNum: 4, title: '调味', content: '加入生抽、老抽、料酒和香料。' },
    { recipeId: 'recipe-braised-pork', orderNum: 5, title: '炖煮', content: '加水没过肉块，小火炖40分钟。' },
    { recipeId: 'recipe-braised-pork', orderNum: 6, title: '收汁', content: '大火收汁至浓稠即可。' },
    { recipeId: 'recipe-broccoli', orderNum: 1, title: '焯水', content: '西兰花焯水2分钟捞出。' },
    { recipeId: 'recipe-broccoli', orderNum: 2, title: '爆香', content: '热锅下油，放入蒜末爆香。' },
    { recipeId: 'recipe-broccoli', orderNum: 3, title: '炒菜', content: '放入西兰花翻炒。' },
    { recipeId: 'recipe-broccoli', orderNum: 4, title: '调味', content: '加盐调味，翻炒均匀即可。' },
    { recipeId: 'recipe-chicken-cola', orderNum: 1, title: '准备', content: '鸡翅洗净，两面划刀。' },
    { recipeId: 'recipe-chicken-cola', orderNum: 2, title: '煎鸡翅', content: '锅中放油，煎至两面金黄。' },
    { recipeId: 'recipe-chicken-cola', orderNum: 3, title: '调味', content: '加入生抽、老抽和姜片。' },
    { recipeId: 'recipe-chicken-cola', orderNum: 4, title: '加可乐', content: '倒入可乐没过鸡翅。' },
    { recipeId: 'recipe-chicken-cola', orderNum: 5, title: '炖煮', content: '大火烧开，转小火炖20分钟。' },
    { recipeId: 'recipe-chicken-cola', orderNum: 6, title: '收汁', content: '大火收汁至浓稠即可。' },
    { recipeId: 'recipe-green-vegetables', orderNum: 1, title: '准备', content: '青菜洗净切段。' },
    { recipeId: 'recipe-green-vegetables', orderNum: 2, title: '爆香', content: '热锅下油，放入蒜末爆香。' },
    { recipeId: 'recipe-green-vegetables', orderNum: 3, title: '炒菜', content: '放入青菜大火快炒。' },
    { recipeId: 'recipe-green-vegetables', orderNum: 4, title: '调味', content: '加盐调味，翻炒均匀即可。' },
    { recipeId: 'recipe-tomato-beef', orderNum: 1, title: '焯水', content: '牛腩切块焯水去腥。' },
    { recipeId: 'recipe-tomato-beef', orderNum: 2, title: '炖肉', content: '牛腩加水炖60分钟至软烂。' },
    { recipeId: 'recipe-tomato-beef', orderNum: 3, title: '准备配菜', content: '番茄和土豆切块。' },
    { recipeId: 'recipe-tomato-beef', orderNum: 4, title: '加入配菜', content: '放入番茄、土豆和番茄酱。' },
    { recipeId: 'recipe-tomato-beef', orderNum: 5, title: '调味', content: '继续炖30分钟，加盐调味。' },
    { recipeId: 'recipe-egg-drop-soup', orderNum: 1, title: '煮水', content: '锅中加水烧开。' },
    { recipeId: 'recipe-egg-drop-soup', orderNum: 2, title: '放紫菜', content: '放入紫菜煮2分钟。' },
    { recipeId: 'recipe-egg-drop-soup', orderNum: 3, title: '倒蛋液', content: '慢慢倒入蛋液，形成蛋花。' },
    { recipeId: 'recipe-egg-drop-soup', orderNum: 4, title: '调味', content: '加盐和香油调味即可。' },
    { recipeId: 'recipe-fried-rice', orderNum: 1, title: '准备', content: '米饭打散，鸡蛋打散备用。' },
    { recipeId: 'recipe-fried-rice', orderNum: 2, title: '炒蛋', content: '热锅下油，倒入蛋液炒散。' },
    { recipeId: 'recipe-fried-rice', orderNum: 3, title: '炒饭', content: '放入米饭大火翻炒。' },
    { recipeId: 'recipe-fried-rice', orderNum: 4, title: '调味', content: '加盐调味，撒上葱花即可。' },
    { recipeId: 'recipe-kung-pao-chicken', orderNum: 1, title: '腌制', content: '鸡胸肉切丁，加生抽、料酒腌制15分钟。' },
    { recipeId: 'recipe-kung-pao-chicken', orderNum: 2, title: '炒花生', content: '锅中放油，小火炒香花生米。' },
    { recipeId: 'recipe-kung-pao-chicken', orderNum: 3, title: '炒鸡肉', content: '锅中加油，放入鸡丁翻炒至变色。' },
    { recipeId: 'recipe-kung-pao-chicken', orderNum: 4, title: '爆香', content: '放入干辣椒、花椒爆香。' },
    { recipeId: 'recipe-kung-pao-chicken', orderNum: 5, title: '调味', content: '加入黄瓜丁、生抽、醋、糖翻炒。' },
    { recipeId: 'recipe-kung-pao-chicken', orderNum: 6, title: '完成', content: '倒入花生米，翻炒均匀即可。' },
    { recipeId: 'recipe-mapo-tofu', orderNum: 1, title: '准备', content: '豆腐切块，焯水备用。' },
    { recipeId: 'recipe-mapo-tofu', orderNum: 2, title: '炒肉末', content: '锅中放油，炒香肉末。' },
    { recipeId: 'recipe-mapo-tofu', orderNum: 3, title: '爆香', content: '加入豆瓣酱、姜蒜末炒出红油。' },
    { recipeId: 'recipe-mapo-tofu', orderNum: 4, title: '炖豆腐', content: '放入豆腐块，加水炖煮5分钟。' },
    { recipeId: 'recipe-mapo-tofu', orderNum: 5, title: '勾芡', content: '倒入水淀粉勾芡。' },
    { recipeId: 'recipe-mapo-tofu', orderNum: 6, title: '完成', content: '撒上花椒粉和葱花即可。' },
    { recipeId: 'recipe-sweet-sour-ribs', orderNum: 1, title: '焯水', content: '排骨冷水下锅焯水去血沫。' },
    { recipeId: 'recipe-sweet-sour-ribs', orderNum: 2, title: '煎排骨', content: '锅中放油，煎至两面金黄。' },
    { recipeId: 'recipe-sweet-sour-ribs', orderNum: 3, title: '调味', content: '加入糖、醋、生抽、料酒。' },
    { recipeId: 'recipe-sweet-sour-ribs', orderNum: 4, title: '炖煮', content: '加水没过排骨，小火炖30分钟。' },
    { recipeId: 'recipe-sweet-sour-ribs', orderNum: 5, title: '收汁', content: '大火收汁至浓稠即可。' },
    { recipeId: 'recipe-yuxiang-pork', orderNum: 1, title: '腌制', content: '猪里脊切丝，加料酒、淀粉腌制。' },
    { recipeId: 'recipe-yuxiang-pork', orderNum: 2, title: '准备配菜', content: '木耳、胡萝卜、青椒切丝。' },
    { recipeId: 'recipe-yuxiang-pork', orderNum: 3, title: '炒肉丝', content: '锅中放油，炒熟肉丝盛出。' },
    { recipeId: 'recipe-yuxiang-pork', orderNum: 4, title: '炒配菜', content: '放入配菜翻炒至断生。' },
    { recipeId: 'recipe-yuxiang-pork', orderNum: 5, title: '调味', content: '加入豆瓣酱、醋、糖、生抽。' },
    { recipeId: 'recipe-yuxiang-pork', orderNum: 6, title: '完成', content: '倒入肉丝翻炒均匀即可。' },
    { recipeId: 'recipe-twice-cooked-pork', orderNum: 1, title: '煮肉', content: '五花肉整块冷水下锅，加姜片、料酒煮20分钟。' },
    { recipeId: 'recipe-twice-cooked-pork', orderNum: 2, title: '切片', content: '肉放凉后切成薄片。' },
    { recipeId: 'recipe-twice-cooked-pork', orderNum: 3, title: '炒肉', content: '锅中放油，放入肉片煸炒至卷曲。' },
    { recipeId: 'recipe-twice-cooked-pork', orderNum: 4, title: '调味', content: '加入豆瓣酱、甜面酱炒出红油。' },
    { recipeId: 'recipe-twice-cooked-pork', orderNum: 5, title: '完成', content: '放入青蒜段翻炒均匀即可。' },
    { recipeId: 'recipe-dry-beans', orderNum: 1, title: '准备', content: '四季豆去筋切段。' },
    { recipeId: 'recipe-dry-beans', orderNum: 2, title: '煸炒', content: '锅中多放油，放入四季豆煸炒至起皱。' },
    { recipeId: 'recipe-dry-beans', orderNum: 3, title: '炒肉末', content: '另起锅炒香肉末。' },
    { recipeId: 'recipe-dry-beans', orderNum: 4, title: '爆香', content: '加入干辣椒、蒜末爆香。' },
    { recipeId: 'recipe-dry-beans', orderNum: 5, title: '完成', content: '倒入四季豆，加盐、生抽翻炒均匀。' },
    { recipeId: 'recipe-steamed-fish', orderNum: 1, title: '准备', content: '鲈鱼洗净，两面划刀，抹上料酒。' },
    { recipeId: 'recipe-steamed-fish', orderNum: 2, title: '铺底', content: '盘中放葱段、姜片，鱼放上面。' },
    { recipeId: 'recipe-steamed-fish', orderNum: 3, title: '蒸鱼', content: '水开后上锅蒸10-12分钟。' },
    { recipeId: 'recipe-steamed-fish', orderNum: 4, title: '倒汁', content: '倒掉蒸出的汤汁，去掉葱姜。' },
    { recipeId: 'recipe-steamed-fish', orderNum: 5, title: '调味', content: '铺上葱丝，淋上蒸鱼豉油。' },
    { recipeId: 'recipe-steamed-fish', orderNum: 6, title: '泼油', content: '烧热油泼在葱丝上即可。' },
    { recipeId: 'recipe-braised-eggplant', orderNum: 1, title: '准备', content: '茄子切块，撒盐腌制10分钟。' },
    { recipeId: 'recipe-braised-eggplant', orderNum: 2, title: '炸茄子', content: '锅中放油，炸至茄子软糯。' },
    { recipeId: 'recipe-braised-eggplant', orderNum: 3, title: '调味', content: '锅中留底油，放入蒜末爆香。' },
    { recipeId: 'recipe-braised-eggplant', orderNum: 4, title: '烧制', content: '加入生抽、老抽、白糖和少许水。' },
    { recipeId: 'recipe-braised-eggplant', orderNum: 5, title: '勾芡', content: '倒入茄子，水淀粉勾芡即可。' },
    { recipeId: 'recipe-tomato-noodle', orderNum: 1, title: '煮面', content: '锅中水烧开，下面条煮至断生。' },
    { recipeId: 'recipe-tomato-noodle', orderNum: 2, title: '炒鸡蛋', content: '热锅下油，炒熟鸡蛋盛出。' },
    { recipeId: 'recipe-tomato-noodle', orderNum: 3, title: '炒番茄', content: '锅中加油，放入番茄炒出汁。' },
    { recipeId: 'recipe-tomato-noodle', orderNum: 4, title: '调味', content: '加入生抽、盐调味。' },
    { recipeId: 'recipe-tomato-noodle', orderNum: 5, title: '完成', content: '倒入鸡蛋和面条，撒上葱花即可。' },
    { recipeId: 'recipe-scallion-noodle', orderNum: 1, title: '熬葱油', content: '锅中放油，小火熬香葱段至焦黄。' },
    { recipeId: 'recipe-scallion-noodle', orderNum: 2, title: '煮面', content: '另起锅煮面至断生。' },
    { recipeId: 'recipe-scallion-noodle', orderNum: 3, title: '调味', content: '生抽、老抽、白糖混合。' },
    { recipeId: 'recipe-scallion-noodle', orderNum: 4, title: '完成', content: '面条捞出，淋上葱油和调料拌匀。' },
    { recipeId: 'recipe-green-pepper-pork', orderNum: 1, title: '腌制', content: '猪里脊切丝，加生抽、料酒、淀粉腌制。' },
    { recipeId: 'recipe-green-pepper-pork', orderNum: 2, title: '切青椒', content: '青椒去籽切丝。' },
    { recipeId: 'recipe-green-pepper-pork', orderNum: 3, title: '炒肉丝', content: '热锅下油，炒熟肉丝盛出。' },
    { recipeId: 'recipe-green-pepper-pork', orderNum: 4, title: '炒青椒', content: '放入青椒丝翻炒至断生。' },
    { recipeId: 'recipe-green-pepper-pork', orderNum: 5, title: '完成', content: '倒入肉丝，加盐翻炒均匀即可。' },
    { recipeId: 'recipe-oyster-lettuce', orderNum: 1, title: '焯水', content: '锅中水烧开，放入生菜焯水30秒。' },
    { recipeId: 'recipe-oyster-lettuce', orderNum: 2, title: '调汁', content: '蚝油、生抽、淀粉、水混合。' },
    { recipeId: 'recipe-oyster-lettuce', orderNum: 3, title: '爆香', content: '热锅下油，放入蒜末爆香。' },
    { recipeId: 'recipe-oyster-lettuce', orderNum: 4, title: '完成', content: '倒入蚝油汁煮至浓稠，淋在生菜上。' },
    { recipeId: 'recipe-hot-sour-soup', orderNum: 1, title: '准备', content: '豆腐、木耳、香菇切丝。' },
    { recipeId: 'recipe-hot-sour-soup', orderNum: 2, title: '煮汤', content: '锅中加水烧开，放入食材煮5分钟。' },
    { recipeId: 'recipe-hot-sour-soup', orderNum: 3, title: '勾芡', content: '倒入水淀粉勾芡。' },
    { recipeId: 'recipe-hot-sour-soup', orderNum: 4, title: '倒蛋液', content: '慢慢倒入蛋液形成蛋花。' },
    { recipeId: 'recipe-hot-sour-soup', orderNum: 5, title: '调味', content: '加醋、胡椒粉、盐调味即可。' },
    { recipeId: 'recipe-winter-melon-soup', orderNum: 1, title: '焯水', content: '排骨冷水下锅焯水去血沫。' },
    { recipeId: 'recipe-winter-melon-soup', orderNum: 2, title: '炖排骨', content: '砂锅中加水，放入排骨、姜片、葱段炖40分钟。' },
    { recipeId: 'recipe-winter-melon-soup', orderNum: 3, title: '加冬瓜', content: '放入冬瓜块继续炖20分钟。' },
    { recipeId: 'recipe-winter-melon-soup', orderNum: 4, title: '调味', content: '加盐调味即可。' },
    { recipeId: 'recipe-cola-ribs', orderNum: 1, title: '焯水', content: '排骨冷水下锅焯水。' },
    { recipeId: 'recipe-cola-ribs', orderNum: 2, title: '煎排骨', content: '锅中放油，煎至两面金黄。' },
    { recipeId: 'recipe-cola-ribs', orderNum: 3, title: '调味', content: '加入生抽、老抽、姜片。' },
    { recipeId: 'recipe-cola-ribs', orderNum: 4, title: '加可乐', content: '倒入可乐没过排骨。' },
    { recipeId: 'recipe-cola-ribs', orderNum: 5, title: '炖煮', content: '大火烧开转小火炖25分钟。' },
    { recipeId: 'recipe-cola-ribs', orderNum: 6, title: '收汁', content: '大火收汁至浓稠即可。' },
    { recipeId: 'recipe-steamed-shrimp', orderNum: 1, title: '准备', content: '粉丝泡软铺在盘底，虾开背去虾线放在粉丝上。' },
    { recipeId: 'recipe-steamed-shrimp', orderNum: 2, title: '炒蒜蓉', content: '锅中放油，炒香蒜末。' },
    { recipeId: 'recipe-steamed-shrimp', orderNum: 3, title: '调味', content: '加入生抽、蚝油混合。' },
    { recipeId: 'recipe-steamed-shrimp', orderNum: 4, title: '淋汁', content: '将蒜蓉汁淋在虾上。' },
    { recipeId: 'recipe-steamed-shrimp', orderNum: 5, title: '蒸制', content: '水开后上锅蒸8-10分钟。' },
    { recipeId: 'recipe-steamed-shrimp', orderNum: 6, title: '完成', content: '撒上葱花即可。' },
    { recipeId: 'recipe-dry-pot-cauliflower', orderNum: 1, title: '准备', content: '花菜掰成小朵，焯水备用。' },
    { recipeId: 'recipe-dry-pot-cauliflower', orderNum: 2, title: '煸肉', content: '锅中放油，放入五花肉片煸炒出油。' },
    { recipeId: 'recipe-dry-pot-cauliflower', orderNum: 3, title: '爆香', content: '加入干辣椒、蒜片爆香。' },
    { recipeId: 'recipe-dry-pot-cauliflower', orderNum: 4, title: '炒花菜', content: '放入花菜翻炒至微焦。' },
    { recipeId: 'recipe-dry-pot-cauliflower', orderNum: 5, title: '调味', content: '加入生抽、蚝油翻炒均匀即可。' },
    { recipeId: 'recipe-three-fresh', orderNum: 1, title: '准备', content: '土豆、茄子、青椒切块。' },
    { recipeId: 'recipe-three-fresh', orderNum: 2, title: '炸土豆', content: '锅中放油，炸至土豆金黄。' },
    { recipeId: 'recipe-three-fresh', orderNum: 3, title: '炸茄子', content: '炸至茄子软糯。' },
    { recipeId: 'recipe-three-fresh', orderNum: 4, title: '调味', content: '锅中留底油，加入生抽、糖、淀粉水。' },
    { recipeId: 'recipe-three-fresh', orderNum: 5, title: '完成', content: '倒入所有食材翻炒均匀即可。' },
    { recipeId: 'recipe-mu-shu-pork', orderNum: 1, title: '腌制', content: '猪里脊切片，加生抽腌制。' },
    { recipeId: 'recipe-mu-shu-pork', orderNum: 2, title: '炒蛋', content: '热锅下油，炒熟鸡蛋盛出。' },
    { recipeId: 'recipe-mu-shu-pork', orderNum: 3, title: '炒肉', content: '放入肉片炒至变色。' },
    { recipeId: 'recipe-mu-shu-pork', orderNum: 4, title: '炒配菜', content: '加入木耳、黄瓜、胡萝卜翻炒。' },
    { recipeId: 'recipe-mu-shu-pork', orderNum: 5, title: '完成', content: '倒入鸡蛋，加盐翻炒均匀即可。' },
    { recipeId: 'recipe-boiled-fish', orderNum: 1, title: '腌制', content: '鱼片加盐、淀粉、蛋清腌制。' },
    { recipeId: 'recipe-boiled-fish', orderNum: 2, title: '焯豆芽', content: '豆芽焯水铺在碗底。' },
    { recipeId: 'recipe-boiled-fish', orderNum: 3, title: '炒底料', content: '锅中放油，炒香豆瓣酱。' },
    { recipeId: 'recipe-boiled-fish', orderNum: 4, title: '煮鱼', content: '加水烧开，放入鱼片煮2分钟。' },
    { recipeId: 'recipe-boiled-fish', orderNum: 5, title: '完成', content: '倒入碗中，撒上干辣椒、花椒，泼热油。' },
    { recipeId: 'recipe-sour-fish', orderNum: 1, title: '腌制', content: '鱼片加盐、淀粉、蛋清腌制。' },
    { recipeId: 'recipe-sour-fish', orderNum: 2, title: '炒酸菜', content: '锅中放油，炒香酸菜、泡椒、姜蒜。' },
    { recipeId: 'recipe-sour-fish', orderNum: 3, title: '煮汤', content: '加水烧开，放入鱼骨煮10分钟。' },
    { recipeId: 'recipe-sour-fish', orderNum: 4, title: '煮鱼片', content: '放入鱼片煮2分钟。' },
    { recipeId: 'recipe-sour-fish', orderNum: 5, title: '完成', content: '倒入碗中，撒上葱花、花椒，泼热油。' },
    { recipeId: 'recipe-braised-hairtail', orderNum: 1, title: '准备', content: '带鱼洗净切段，抹上盐腌制10分钟。' },
    { recipeId: 'recipe-braised-hairtail', orderNum: 2, title: '煎带鱼', content: '锅中放油，煎至两面金黄。' },
    { recipeId: 'recipe-braised-hairtail', orderNum: 3, title: '调味', content: '加入姜片、葱段、生抽、老抽、料酒。' },
    { recipeId: 'recipe-braised-hairtail', orderNum: 4, title: '炖煮', content: '加水没过带鱼，小火炖15分钟。' },
    { recipeId: 'recipe-braised-hairtail', orderNum: 5, title: '收汁', content: '大火收汁至浓稠即可。' },
    { recipeId: 'recipe-sweet-sour-loin', orderNum: 1, title: '腌制', content: '里脊肉切条，加盐腌制。' },
    { recipeId: 'recipe-sweet-sour-loin', orderNum: 2, title: '挂糊', content: '裹上淀粉和蛋清的混合物。' },
    { recipeId: 'recipe-sweet-sour-loin', orderNum: 3, title: '炸制', content: '锅中放油，炸至金黄酥脆。' },
    { recipeId: 'recipe-sweet-sour-loin', orderNum: 4, title: '调汁', content: '糖、醋、番茄酱、淀粉水混合。' },
    { recipeId: 'recipe-sweet-sour-loin', orderNum: 5, title: '完成', content: '锅中倒入糖醋汁煮至浓稠，放入里脊翻炒。' },
    { recipeId: 'recipe-yuxiang-eggplant', orderNum: 1, title: '准备', content: '茄子切条，撒盐腌制10分钟。' },
    { recipeId: 'recipe-yuxiang-eggplant', orderNum: 2, title: '炸茄子', content: '锅中放油，炸至茄子软糯。' },
    { recipeId: 'recipe-yuxiang-eggplant', orderNum: 3, title: '炒肉末', content: '另起锅炒香肉末。' },
    { recipeId: 'recipe-yuxiang-eggplant', orderNum: 4, title: '调味', content: '加入豆瓣酱、醋、糖、生抽、蒜末。' },
    { recipeId: 'recipe-yuxiang-eggplant', orderNum: 5, title: '完成', content: '倒入茄子翻炒均匀即可。' },
    { recipeId: 'recipe-garlic-pork', orderNum: 1, title: '煮肉', content: '五花肉整块冷水下锅煮30分钟。' },
    { recipeId: 'recipe-garlic-pork', orderNum: 2, title: '切片', content: '肉放凉后切成薄片。' },
    { recipeId: 'recipe-garlic-pork', orderNum: 3, title: '调汁', content: '蒜末、辣椒油、生抽、醋、糖混合。' },
    { recipeId: 'recipe-garlic-pork', orderNum: 4, title: '完成', content: '将蒜泥汁淋在肉片上即可。' },
    { recipeId: 'recipe-dry-beef', orderNum: 1, title: '腌制', content: '牛肉切丝，加料酒、生抽腌制。' },
    { recipeId: 'recipe-dry-beef', orderNum: 2, title: '煸炒', content: '锅中放油，放入牛肉丝煸炒至干香。' },
    { recipeId: 'recipe-dry-beef', orderNum: 3, title: '爆香', content: '加入干辣椒、花椒、姜蒜丝爆香。' },
    { recipeId: 'recipe-dry-beef', orderNum: 4, title: '调味', content: '加生抽、盐翻炒均匀即可。' },
    { recipeId: 'recipe-scallion-lamb', orderNum: 1, title: '准备', content: '羊肉切片，大葱切段。' },
    { recipeId: 'recipe-scallion-lamb', orderNum: 2, title: '炒羊肉', content: '热锅下油，大火炒羊肉至变色。' },
    { recipeId: 'recipe-scallion-lamb', orderNum: 3, title: '调味', content: '加入生抽、料酒翻炒。' },
    { recipeId: 'recipe-scallion-lamb', orderNum: 4, title: '完成', content: '放入大葱段，加盐、胡椒粉翻炒均匀。' },
    { recipeId: 'recipe-kung-pao-shrimp', orderNum: 1, title: '准备', content: '虾去壳去虾线，加料酒腌制。' },
    { recipeId: 'recipe-kung-pao-shrimp', orderNum: 2, title: '炒花生', content: '小火炒香花生米。' },
    { recipeId: 'recipe-kung-pao-shrimp', orderNum: 3, title: '炒虾', content: '热锅下油，炒熟虾球盛出。' },
    { recipeId: 'recipe-kung-pao-shrimp', orderNum: 4, title: '爆香', content: '放入干辣椒、花椒爆香。' },
    { recipeId: 'recipe-kung-pao-shrimp', orderNum: 5, title: '调味', content: '加入黄瓜丁、生抽、醋、糖。' },
    { recipeId: 'recipe-kung-pao-shrimp', orderNum: 6, title: '完成', content: '倒入虾球和花生米翻炒均匀。' },
    { recipeId: 'recipe-steamed-luffa', orderNum: 1, title: '准备', content: '丝瓜去皮切段，摆在盘中。' },
    { recipeId: 'recipe-steamed-luffa', orderNum: 2, title: '炒蒜蓉', content: '锅中放油，炒香蒜末。' },
    { recipeId: 'recipe-steamed-luffa', orderNum: 3, title: '淋汁', content: '将蒜蓉和生抽淋在丝瓜上。' },
    { recipeId: 'recipe-steamed-luffa', orderNum: 4, title: '蒸制', content: '水开后上锅蒸10分钟。' },
    { recipeId: 'recipe-steamed-luffa', orderNum: 5, title: '完成', content: '撒上葱花，泼热油即可。' },
    { recipeId: 'recipe-oyster-beef', orderNum: 1, title: '腌制', content: '牛肉切片，加生抽、淀粉腌制。' },
    { recipeId: 'recipe-oyster-beef', orderNum: 2, title: '炒牛肉', content: '热锅下油，炒熟牛肉盛出。' },
    { recipeId: 'recipe-oyster-beef', orderNum: 3, title: '炒配菜', content: '放入姜蒜、青椒翻炒。' },
    { recipeId: 'recipe-oyster-beef', orderNum: 4, title: '调味', content: '加入蚝油、生抽。' },
    { recipeId: 'recipe-oyster-beef', orderNum: 5, title: '完成', content: '倒入牛肉翻炒均匀即可。' },
    { recipeId: 'recipe-braised-tofu', orderNum: 1, title: '准备', content: '豆腐切块。' },
    { recipeId: 'recipe-braised-tofu', orderNum: 2, title: '煎豆腐', content: '锅中放油，煎至两面金黄。' },
    { recipeId: 'recipe-braised-tofu', orderNum: 3, title: '爆香', content: '放入蒜末爆香。' },
    { recipeId: 'recipe-braised-tofu', orderNum: 4, title: '调味', content: '加入生抽、老抽、白糖和少许水。' },
    { recipeId: 'recipe-braised-tofu', orderNum: 5, title: '完成', content: '倒入豆腐，水淀粉勾芡即可。' },
    { recipeId: 'recipe-dry-pot-potato', orderNum: 1, title: '准备', content: '土豆切片，焯水备用。' },
    { recipeId: 'recipe-dry-pot-potato', orderNum: 2, title: '煎土豆', content: '锅中放油，煎至两面金黄。' },
    { recipeId: 'recipe-dry-pot-potato', orderNum: 3, title: '煸肉', content: '放入五花肉片煸炒出油。' },
    { recipeId: 'recipe-dry-pot-potato', orderNum: 4, title: '爆香', content: '加入干辣椒、花椒、蒜片爆香。' },
    { recipeId: 'recipe-dry-pot-potato', orderNum: 5, title: '调味', content: '加入生抽翻炒均匀即可。' },
    { recipeId: 'recipe-roasted-eggplant', orderNum: 1, title: '准备', content: '茄子洗净，表面划几刀。' },
    { recipeId: 'recipe-roasted-eggplant', orderNum: 2, title: '烤茄子', content: '烤箱200度烤15分钟至软。' },
    { recipeId: 'recipe-roasted-eggplant', orderNum: 3, title: '炒蒜蓉', content: '锅中放油，炒香蒜末。' },
    { recipeId: 'recipe-roasted-eggplant', orderNum: 4, title: '调味', content: '加入生抽、蚝油混合。' },
    { recipeId: 'recipe-roasted-eggplant', orderNum: 5, title: '完成', content: '将蒜蓉汁淋在茄子上，撒葱花。' },
    { recipeId: 'recipe-tomato-egg-soup', orderNum: 1, title: '炒番茄', content: '锅中放油，放入番茄炒出汁。' },
    { recipeId: 'recipe-tomato-egg-soup', orderNum: 2, title: '煮汤', content: '加水烧开。' },
    { recipeId: 'recipe-tomato-egg-soup', orderNum: 3, title: '倒蛋液', content: '慢慢倒入蛋液形成蛋花。' },
    { recipeId: 'recipe-tomato-egg-soup', orderNum: 4, title: '调味', content: '加盐、糖调味，撒上葱花。' },
    { recipeId: 'recipe-lotus-root-soup', orderNum: 1, title: '焯水', content: '排骨冷水下锅焯水。' },
    { recipeId: 'recipe-lotus-root-soup', orderNum: 2, title: '炖排骨', content: '砂锅中加水，放入排骨、姜片炖40分钟。' },
    { recipeId: 'recipe-lotus-root-soup', orderNum: 3, title: '加莲藕', content: '放入莲藕块炖20分钟。' },
    { recipeId: 'recipe-lotus-root-soup', orderNum: 4, title: '调味', content: '加盐调味即可。' },
    { recipeId: 'recipe-radish-beef', orderNum: 1, title: '焯水', content: '牛腩切块，冷水下锅焯水。' },
    { recipeId: 'recipe-radish-beef', orderNum: 2, title: '炒糖色', content: '锅中放油和冰糖，炒至焦糖色。' },
    { recipeId: 'recipe-radish-beef', orderNum: 3, title: '炒牛腩', content: '放入牛腩翻炒上色。' },
    { recipeId: 'recipe-radish-beef', orderNum: 4, title: '调味', content: '加入生抽、老抽、料酒、八角、桂皮。' },
    { recipeId: 'recipe-radish-beef', orderNum: 5, title: '炖煮', content: '加水没过牛腩，小火炖1小时。' },
    { recipeId: 'recipe-radish-beef', orderNum: 6, title: '加萝卜', content: '放入萝卜块继续炖20分钟。' },
    { recipeId: 'recipe-plum-pork', orderNum: 1, title: '煮肉', content: '五花肉整块冷水下锅煮30分钟。' },
    { recipeId: 'recipe-plum-pork', orderNum: 2, title: '上色', content: '肉表面抹上老抽，炸至金黄。' },
    { recipeId: 'recipe-plum-pork', orderNum: 3, title: '切片', content: '肉放凉后切成薄片。' },
    { recipeId: 'recipe-plum-pork', orderNum: 4, title: '铺底', content: '梅菜铺在碗底，肉片码在上面。' },
    { recipeId: 'recipe-plum-pork', orderNum: 5, title: '调味', content: '淋上生抽、料酒、糖的混合汁。' },
    { recipeId: 'recipe-plum-pork', orderNum: 6, title: '蒸制', content: '上锅蒸1.5小时，倒扣装盘。' },
    { recipeId: 'recipe-dongpo-pork', orderNum: 1, title: '焯水', content: '五花肉整块冷水下锅焯水。' },
    { recipeId: 'recipe-dongpo-pork', orderNum: 2, title: '铺底', content: '砂锅底部铺上姜片和葱段。' },
    { recipeId: 'recipe-dongpo-pork', orderNum: 3, title: '放肉', content: '放入五花肉，皮朝下。' },
    { recipeId: 'recipe-dongpo-pork', orderNum: 4, title: '调味', content: '加入黄酒、生抽、老抽、冰糖。' },
    { recipeId: 'recipe-dongpo-pork', orderNum: 5, title: '炖煮', content: '小火炖2小时，翻面再炖30分钟。' },
    { recipeId: 'recipe-dongpo-pork', orderNum: 6, title: '收汁', content: '大火收汁至浓稠即可。' },
    { recipeId: 'recipe-mouth-water-chicken', orderNum: 1, title: '煮鸡', content: '鸡腿冷水下锅煮15分钟至熟。' },
    { recipeId: 'recipe-mouth-water-chicken', orderNum: 2, title: '过冰水', content: '捞出放入冰水中冷却。' },
    { recipeId: 'recipe-mouth-water-chicken', orderNum: 3, title: '调汁', content: '辣椒油、生抽、醋、花椒粉混合。' },
    { recipeId: 'recipe-mouth-water-chicken', orderNum: 4, title: '完成', content: '将调料淋在鸡块上，撒花生碎、葱花。' }
  ];

  for (const step of steps) {
    await query(
      'INSERT INTO steps (id, recipeId, orderNum, title, content) VALUES (UUID(), ?, ?, ?, ?)',
      [step.recipeId, step.orderNum, step.title, step.content]
    );
  }

  console.log('示例数据插入完成，共插入50个菜谱');
}

initDatabase();